from .models.models import Carriage, CarriageType, Flight, LocationType, Seat, Ticket, Train, TrainType, Location

fixtures_data = {
    Train: [
        #Поезд 1
        {"id": 1, "number": "001", "type": TrainType.TRAIN},

        #Поезд 2
        {"id": 2, "number": "002", "type": TrainType.ELECTRIC_TRAIN}
    ],
    Carriage: [
        #Поезд 1 Вагоны
        {"id": 1, "train_id": 1, "number": "01", "type": CarriageType.RESERVED_SEAT},
        {"id": 2, "train_id": 1, "number": "02", "type": CarriageType.RESERVED_SEAT},
        {"id": 3, "train_id": 1, "number": "03", "type": CarriageType.RESERVED_SEAT},
        {"id": 4, "train_id": 1, "number": "04", "type": CarriageType.RESERVED_SEAT},
        {"id": 5, "train_id": 1, "number": "05", "type": CarriageType.FC},

        #Поезд 2 Вагоны
        {"id": 6, "train_id": 2, "number": "01", "type": CarriageType.SEDENTARY},
        {"id": 7, "train_id": 2, "number": "02", "type": CarriageType.SEDENTARY},
        {"id": 8, "train_id": 2, "number": "03", "type": CarriageType.SEDENTARY}
    ],
    Seat: [
        # Поезд 1 Вагон 1
        {"id": 1, "number": "001", "carriage_id": 1}, {"id": 2, "number": "002", "carriage_id": 1}, 
        {"id": 3, "number": "003", "carriage_id": 1}, {"id": 4, "number": "004", "carriage_id": 1},
        {"id": 5, "number": "005", "carriage_id": 1}, {"id": 6, "number": "006", "carriage_id": 1}, 
        {"id": 7, "number": "007", "carriage_id": 1}, {"id": 8, "number": "008", "carriage_id": 1}, 
        {"id": 9, "number": "009", "carriage_id": 1}, {"id": 10, "number": "010", "carriage_id": 1}, 
        {"id": 11, "number": "011", "carriage_id": 1}, {"id": 12, "number": "012", "carriage_id": 1}, 

        # Поезд 1 Вагон 2
        {"id": 13, "number": "013", "carriage_id":2}, {"id": 14, "number": "014", "carriage_id":2}, 
        {"id": 15, "number": "015", "carriage_id":2}, {"id": 16, "number": "016", "carriage_id":2},
        {"id": 17, "number": "017", "carriage_id":2}, {"id": 18, "number": "018", "carriage_id":2}, 
        {"id": 19, "number": "019", "carriage_id":2}, {"id": 20, "number": "020", "carriage_id":2}, 
        {"id": 21, "number": "021", "carriage_id":2}, {"id": 22, "number": "022", "carriage_id":2}, 
        {"id": 23, "number": "023", "carriage_id":2}, {"id": 24, "number": "024", "carriage_id":2},

        # Поезд 1 Вагон 3
        {"id": 25, "number": "025", "carriage_id":3}, {"id": 26, "number": "026", "carriage_id":3}, 
        {"id": 27, "number": "027", "carriage_id":3}, {"id": 28, "number": "028", "carriage_id":3},
        {"id": 29, "number": "029", "carriage_id":3}, {"id": 30, "number": "030", "carriage_id":3}, 
        {"id": 31, "number": "031", "carriage_id":3}, {"id": 32, "number": "032", "carriage_id":3}, 
        {"id": 33, "number": "033", "carriage_id":3}, {"id": 34, "number": "034", "carriage_id":3}, 
        {"id": 35, "number": "035", "carriage_id":3}, {"id": 36, "number": "036", "carriage_id":3}, 

        # Поезд 1 Вагон 4
        {"id": 37, "number": "037", "carriage_id":4}, {"id": 38, "number": "038", "carriage_id":4}, 
        {"id": 39, "number": "039", "carriage_id":4}, {"id": 40, "number": "040", "carriage_id":4},
        {"id": 41, "number": "041", "carriage_id":4}, {"id": 42, "number": "042", "carriage_id":4}, 
        {"id": 43, "number": "043", "carriage_id":4}, {"id": 44, "number": "044", "carriage_id":4}, 
        {"id": 45, "number": "045", "carriage_id":4}, {"id": 46, "number": "046", "carriage_id":4}, 
        {"id": 47, "number": "047", "carriage_id":4}, {"id": 48, "number": "048", "carriage_id":4},

        # Поезд 1 Вагон 5
        {"id": 49, "number": "049", "carriage_id":5}, {"id": 50, "number": "050", "carriage_id":5}, 
        {"id": 51, "number": "051", "carriage_id":5}, {"id": 52, "number": "052", "carriage_id":5},
        {"id": 53, "number": "053", "carriage_id":5}, {"id": 54, "number": "054", "carriage_id":5}, 
        {"id": 55, "number": "055", "carriage_id":5}, {"id": 56, "number": "056", "carriage_id":5}, 
        {"id": 57, "number": "057", "carriage_id":5}, {"id": 58, "number": "058", "carriage_id":5}, 
        {"id": 59, "number": "059", "carriage_id":5}, {"id": 60, "number": "060", "carriage_id":5},

        # Поезд 2 Вагон 1
        {"id": 61, "number": "001", "carriage_id":6}, {"id": 62, "number": "002", "carriage_id":6}, 
        {"id": 63, "number": "003", "carriage_id":6}, {"id": 64, "number": "004", "carriage_id":6},
        {"id": 65, "number": "005", "carriage_id":6}, {"id": 66, "number": "006", "carriage_id":6}, 
        {"id": 67, "number": "007", "carriage_id":6}, {"id": 68, "number": "008", "carriage_id":6}, 
        {"id": 69, "number": "009", "carriage_id":6}, {"id": 70, "number": "010", "carriage_id":6}, 
        {"id": 71, "number": "011", "carriage_id":6}, {"id": 72, "number": "012", "carriage_id":6}, 

        # Поезд 2 Вагон 2
        {"id": 73, "number": "013", "carriage_id":7}, {"id": 74, "number": "014", "carriage_id":7}, 
        {"id": 75, "number": "015", "carriage_id":7}, {"id": 76, "number": "016", "carriage_id":7},
        {"id": 77, "number": "017", "carriage_id":7}, {"id": 78, "number": "018", "carriage_id":7}, 
        {"id": 79, "number": "019", "carriage_id":7}, {"id": 80, "number": "020", "carriage_id":7}, 
        {"id": 81, "number": "021", "carriage_id":7}, {"id": 82, "number": "022", "carriage_id":7}, 
        {"id": 83, "number": "023", "carriage_id":7}, {"id": 84, "number": "024", "carriage_id":7},

        # Поезд 2 Вагон 3
        {"id": 85, "number": "025", "carriage_id":8}, {"id": 86, "number": "026", "carriage_id":8}, 
        {"id": 87, "number": "027", "carriage_id":8}, {"id": 88, "number": "028", "carriage_id":8},
        {"id": 89, "number": "029", "carriage_id":8}, {"id": 90, "number": "030", "carriage_id":8}, 
        {"id": 91, "number": "031", "carriage_id":8}, {"id": 92, "number": "032", "carriage_id":8}, 
        {"id": 93, "number": "033", "carriage_id":8}, {"id": 94, "number": "034", "carriage_id":8}, 
        {"id": 95, "number": "035", "carriage_id":8}, {"id": 96, "number": "036", "carriage_id":8}
    ],
    Location: [
        #Города России
        {'id': 1, 'title': 'Абаза', 'type': LocationType.CITY},
        {'id': 2, 'title': 'Абакан', 'type': LocationType.CITY},
        {'id': 3, 'title': 'Абдулино', 'type': LocationType.CITY},
        {'id': 4, 'title': 'Абинск', 'type': LocationType.CITY},
        {'id': 5, 'title': 'Агидель', 'type': LocationType.CITY},
        {'id': 6, 'title': 'Агрыз', 'type': LocationType.CITY},
        {'id': 7, 'title': 'Адыгейск', 'type': LocationType.CITY},
        {'id': 8, 'title': 'Азнакаево', 'type': LocationType.CITY},
        {'id': 9, 'title': 'Азов', 'type': LocationType.CITY},
        {'id': 10, 'title': 'Ак-Довурак', 'type': LocationType.CITY},
        {'id': 11, 'title': 'Аксай', 'type': LocationType.CITY},
        {'id': 12, 'title': 'Алагир', 'type': LocationType.CITY},
        {'id': 13, 'title': 'Алапаевск', 'type': LocationType.CITY},
        {'id': 14, 'title': 'Алатырь', 'type': LocationType.CITY},
        {'id': 15, 'title': 'Алдан', 'type': LocationType.CITY},
        {'id': 16, 'title': 'Алейск', 'type': LocationType.CITY},
        {'id': 17, 'title': 'Александров', 'type': LocationType.CITY},
        {'id': 18, 'title': 'Александровск', 'type': LocationType.CITY},
        {'id': 19, 'title': 'Александровск-Сахалинский', 'type': LocationType.CITY},
        {'id': 20, 'title': 'Алексеевка', 'type': LocationType.CITY},
        {'id': 21, 'title': 'Алексин', 'type': LocationType.CITY},
        {'id': 22, 'title': 'Алзамай', 'type': LocationType.CITY},
        {'id': 23, 'title': 'Алупка', 'type': LocationType.CITY},
        {'id': 24, 'title': 'Алушта', 'type': LocationType.CITY},
        {'id': 25, 'title': 'Альметьевск', 'type': LocationType.CITY},
        {'id': 26, 'title': 'Амурск', 'type': LocationType.CITY},
        {'id': 27, 'title': 'Анадырь', 'type': LocationType.CITY},
        {'id': 28, 'title': 'Анапа', 'type': LocationType.CITY},
        {'id': 29, 'title': 'Ангарск', 'type': LocationType.CITY},
        {'id': 30, 'title': 'Андреаполь', 'type': LocationType.CITY},
        {'id': 31, 'title': 'Анжеро-Судженск', 'type': LocationType.CITY},
        {'id': 32, 'title': 'Анива', 'type': LocationType.CITY},
        {'id': 33, 'title': 'Апатиты', 'type': LocationType.CITY},
        {'id': 34, 'title': 'Апрелевка', 'type': LocationType.CITY},
        {'id': 35, 'title': 'Апшеронск', 'type': LocationType.CITY},
        {'id': 36, 'title': 'Арамиль', 'type': LocationType.CITY},
        {'id': 37, 'title': 'Аргун', 'type': LocationType.CITY},
        {'id': 38, 'title': 'Ардатов', 'type': LocationType.CITY},
        {'id': 39, 'title': 'Ардон', 'type': LocationType.CITY},
        {'id': 40, 'title': 'Арзамас', 'type': LocationType.CITY},
        {'id': 41, 'title': 'Аркадак', 'type': LocationType.CITY},
        {'id': 42, 'title': 'Армавир', 'type': LocationType.CITY},
        {'id': 43, 'title': 'Армянск', 'type': LocationType.CITY},
        {'id': 44, 'title': 'Арсеньев', 'type': LocationType.CITY},
        {'id': 45, 'title': 'Арск', 'type': LocationType.CITY},
        {'id': 46, 'title': 'Артём', 'type': LocationType.CITY},
        {'id': 47, 'title': 'Артёмовск', 'type': LocationType.CITY},
        {'id': 48, 'title': 'Артёмовский', 'type': LocationType.CITY},
        {'id': 49, 'title': 'Архангельск', 'type': LocationType.CITY},
        {'id': 50, 'title': 'Асбест', 'type': LocationType.CITY},
        {'id': 51, 'title': 'Асино', 'type': LocationType.CITY},
        {'id': 52, 'title': 'Астрахань', 'type': LocationType.CITY},
        {'id': 53, 'title': 'Аткарск', 'type': LocationType.CITY},
        {'id': 54, 'title': 'Ахтубинск', 'type': LocationType.CITY},
        {'id': 55, 'title': 'Ачинск', 'type': LocationType.CITY},
        {'id': 56, 'title': 'Ачхой-Мартан', 'type': LocationType.CITY},
        {'id': 57, 'title': 'Аша', 'type': LocationType.CITY},
        {'id': 58, 'title': 'Бабаево', 'type': LocationType.CITY},
        {'id': 59, 'title': 'Бабушкин', 'type': LocationType.CITY},
        {'id': 60, 'title': 'Бавлы', 'type': LocationType.CITY},
        {'id': 61, 'title': 'Багратионовск', 'type': LocationType.CITY},
        {'id': 62, 'title': 'Байкальск', 'type': LocationType.CITY},
        {'id': 63, 'title': 'Баймак', 'type': LocationType.CITY},
        {'id': 64, 'title': 'Бакал', 'type': LocationType.CITY},
        {'id': 65, 'title': 'Баксан', 'type': LocationType.CITY},
        {'id': 66, 'title': 'Балабаново', 'type': LocationType.CITY},
        {'id': 67, 'title': 'Балаково', 'type': LocationType.CITY},
        {'id': 68, 'title': 'Балахна', 'type': LocationType.CITY},
        {'id': 69, 'title': 'Балашиха', 'type': LocationType.CITY},
        {'id': 70, 'title': 'Балашов', 'type': LocationType.CITY},
        {'id': 71, 'title': 'Балей', 'type': LocationType.CITY},
        {'id': 72, 'title': 'Балтийск', 'type': LocationType.CITY},
        {'id': 73, 'title': 'Барабинск', 'type': LocationType.CITY},
        {'id': 74, 'title': 'Барнаул', 'type': LocationType.CITY},
        {'id': 75, 'title': 'Барыш', 'type': LocationType.CITY},
        {'id': 76, 'title': 'Батайск', 'type': LocationType.CITY},
        {'id': 77, 'title': 'Бахчисарай', 'type': LocationType.CITY},
        {'id': 78, 'title': 'Бежецк', 'type': LocationType.CITY},
        {'id': 79, 'title': 'Белая Калитва', 'type': LocationType.CITY},
        {'id': 80, 'title': 'Белая Холуница', 'type': LocationType.CITY},
        {'id': 81, 'title': 'Белгород', 'type': LocationType.CITY},
        {'id': 82, 'title': 'Белебей', 'type': LocationType.CITY},
        {'id': 83, 'title': 'Белёв', 'type': LocationType.CITY},
        {'id': 84, 'title': 'Белинский', 'type': LocationType.CITY},
        {'id': 85, 'title': 'Белово', 'type': LocationType.CITY},
        {'id': 86, 'title': 'Белогорск', 'type': LocationType.CITY},
        {'id': 87, 'title': 'Белогорск (Не признанный)', 'type': LocationType.CITY},
        {'id': 88, 'title': 'Белозерск', 'type': LocationType.CITY},
        {'id': 89, 'title': 'Белокуриха', 'type': LocationType.CITY},
        {'id': 90, 'title': 'Беломорск', 'type': LocationType.CITY},
        {'id': 91, 'title': 'Белоозёрский', 'type': LocationType.CITY},
        {'id': 92, 'title': 'Белорецк', 'type': LocationType.CITY},
        {'id': 93, 'title': 'Белореченск', 'type': LocationType.CITY},
        {'id': 94, 'title': 'Белоусово', 'type': LocationType.CITY},
        {'id': 95, 'title': 'Белоярский', 'type': LocationType.CITY},
        {'id': 96, 'title': 'Белый', 'type': LocationType.CITY},
        {'id': 97, 'title': 'Бердск', 'type': LocationType.CITY},
        {'id': 98, 'title': 'Березники', 'type': LocationType.CITY},
        {'id': 99, 'title': 'Берёзовский (Кемеровская область)', 'type': LocationType.CITY},
        {'id': 100, 'title': 'Берёзовский (Свердловская область)', 'type': LocationType.CITY},
        {'id': 101, 'title': 'Беслан', 'type': LocationType.CITY},
        {'id': 102, 'title': 'Бийск', 'type': LocationType.CITY},
        {'id': 103, 'title': 'Бикин', 'type': LocationType.CITY},
        {'id': 104, 'title': 'Билибино', 'type': LocationType.CITY},
        {'id': 105, 'title': 'Биробиджан', 'type': LocationType.CITY},
        {'id': 106, 'title': 'Бирск', 'type': LocationType.CITY},
        {'id': 107, 'title': 'Бирюсинск', 'type': LocationType.CITY},
        {'id': 108, 'title': 'Бирюч', 'type': LocationType.CITY},
        {'id': 109, 'title': 'Благовещенск (Башкортостан)', 'type': LocationType.CITY},
        {'id': 110, 'title': 'Благовещенск (Амурская область)', 'type': LocationType.CITY},
        {'id': 111, 'title': 'Благодарный', 'type': LocationType.CITY},
        {'id': 112, 'title': 'Бобров', 'type': LocationType.CITY},
        {'id': 113, 'title': 'Богданович', 'type': LocationType.CITY},
        {'id': 114, 'title': 'Богородицк', 'type': LocationType.CITY},
        {'id': 115, 'title': 'Богородск', 'type': LocationType.CITY},
        {'id': 116, 'title': 'Боготол', 'type': LocationType.CITY},
        {'id': 117, 'title': 'Богучар', 'type': LocationType.CITY},
        {'id': 118, 'title': 'Бодайбо', 'type': LocationType.CITY},
        {'id': 119, 'title': 'Бокситогорск', 'type': LocationType.CITY},
        {'id': 120, 'title': 'Болгар', 'type': LocationType.CITY},
        {'id': 121, 'title': 'Бологое', 'type': LocationType.CITY},
        {'id': 122, 'title': 'Болотное', 'type': LocationType.CITY},
        {'id': 123, 'title': 'Болохово', 'type': LocationType.CITY},
        {'id': 124, 'title': 'Болхов', 'type': LocationType.CITY},
        {'id': 125, 'title': 'Большой Камень', 'type': LocationType.CITY},
        {'id': 126, 'title': 'Бор', 'type': LocationType.CITY},
        {'id': 127, 'title': 'Борзя', 'type': LocationType.CITY},
        {'id': 128, 'title': 'Борисоглебск', 'type': LocationType.CITY},
        {'id': 129, 'title': 'Боровичи', 'type': LocationType.CITY},
        {'id': 130, 'title': 'Боровск', 'type': LocationType.CITY},
        {'id': 131, 'title': 'Бородино', 'type': LocationType.CITY},
        {'id': 132, 'title': 'Братск', 'type': LocationType.CITY},
        {'id': 133, 'title': 'Бронницы', 'type': LocationType.CITY},
        {'id': 134, 'title': 'Брянск', 'type': LocationType.CITY},
        {'id': 135, 'title': 'Бугульма', 'type': LocationType.CITY},
        {'id': 136, 'title': 'Бугуруслан', 'type': LocationType.CITY},
        {'id': 137, 'title': 'Будённовск', 'type': LocationType.CITY},
        {'id': 138, 'title': 'Бузулук', 'type': LocationType.CITY},
        {'id': 139, 'title': 'Буинск', 'type': LocationType.CITY},
        {'id': 140, 'title': 'Буй', 'type': LocationType.CITY},
        {'id': 141, 'title': 'Буйнакск', 'type': LocationType.CITY},
        {'id': 142, 'title': 'Бутурлиновка', 'type': LocationType.CITY},
        {'id': 143, 'title': 'Валдай', 'type': LocationType.CITY},
        {'id': 144, 'title': 'Валуйки', 'type': LocationType.CITY},
        {'id': 145, 'title': 'Велиж', 'type': LocationType.CITY},
        {'id': 146, 'title': 'Великие Луки', 'type': LocationType.CITY},
        {'id': 147, 'title': 'Великий Новгород', 'type': LocationType.CITY},
        {'id': 148, 'title': 'Великий Устюг', 'type': LocationType.CITY},
        {'id': 149, 'title': 'Вельск', 'type': LocationType.CITY},
        {'id': 150, 'title': 'Венёв', 'type': LocationType.CITY},
        {'id': 151, 'title': 'Верещагино', 'type': LocationType.CITY},
        {'id': 152, 'title': 'Верея', 'type': LocationType.CITY},
        {'id': 153, 'title': 'Верхнеуральск', 'type': LocationType.CITY},
        {'id': 154, 'title': 'Верхний Тагил', 'type': LocationType.CITY},
        {'id': 155, 'title': 'Верхний Уфалей', 'type': LocationType.CITY},
        {'id': 156, 'title': 'Верхняя Пышма', 'type': LocationType.CITY},
        {'id': 157, 'title': 'Верхняя Салда', 'type': LocationType.CITY},
        {'id': 158, 'title': 'Верхняя Тура', 'type': LocationType.CITY},
        {'id': 159, 'title': 'Верхотурье', 'type': LocationType.CITY},
        {'id': 160, 'title': 'Верхоянск', 'type': LocationType.CITY},
        {'id': 161, 'title': 'Весьегонск', 'type': LocationType.CITY},
        {'id': 162, 'title': 'Ветлуга', 'type': LocationType.CITY},
        {'id': 163, 'title': 'Видное', 'type': LocationType.CITY},
        {'id': 164, 'title': 'Вилюйск', 'type': LocationType.CITY},
        {'id': 165, 'title': 'Вилючинск', 'type': LocationType.CITY},
        {'id': 166, 'title': 'Вихоревка', 'type': LocationType.CITY},
        {'id': 167, 'title': 'Вичуга', 'type': LocationType.CITY},
        {'id': 168, 'title': 'Владивосток', 'type': LocationType.CITY},
        {'id': 169, 'title': 'Владикавказ', 'type': LocationType.CITY},
        {'id': 170, 'title': 'Владимир', 'type': LocationType.CITY},
        {'id': 171, 'title': 'Волгоград', 'type': LocationType.CITY},
        {'id': 172, 'title': 'Волгодонск', 'type': LocationType.CITY},
        {'id': 173, 'title': 'Волгореченск', 'type': LocationType.CITY},
        {'id': 174, 'title': 'Волжск', 'type': LocationType.CITY},
        {'id': 175, 'title': 'Волжский', 'type': LocationType.CITY},
        {'id': 176, 'title': 'Вологда', 'type': LocationType.CITY},
        {'id': 177, 'title': 'Володарск', 'type': LocationType.CITY},
        {'id': 178, 'title': 'Волоколамск', 'type': LocationType.CITY},
        {'id': 179, 'title': 'Волосово', 'type': LocationType.CITY},
        {'id': 180, 'title': 'Волхов', 'type': LocationType.CITY},
        {'id': 181, 'title': 'Волчанск', 'type': LocationType.CITY},
        {'id': 182, 'title': 'Вольск', 'type': LocationType.CITY},
        {'id': 183, 'title': 'Воркута', 'type': LocationType.CITY},
        {'id': 184, 'title': 'Воронеж', 'type': LocationType.CITY},
        {'id': 185, 'title': 'Ворсма', 'type': LocationType.CITY},
        {'id': 186, 'title': 'Воскресенск', 'type': LocationType.CITY},
        {'id': 187, 'title': 'Воткинск', 'type': LocationType.CITY},
        {'id': 188, 'title': 'Всеволожск', 'type': LocationType.CITY},
        {'id': 189, 'title': 'Вуктыл', 'type': LocationType.CITY},
        {'id': 190, 'title': 'Выборг', 'type': LocationType.CITY},
        {'id': 191, 'title': 'Выкса', 'type': LocationType.CITY},
        {'id': 192, 'title': 'Высоковск', 'type': LocationType.CITY},
        {'id': 193, 'title': 'Высоцк', 'type': LocationType.CITY},
        {'id': 194, 'title': 'Вытегра', 'type': LocationType.CITY},
        {'id': 195, 'title': 'Вышний Волочёк', 'type': LocationType.CITY},
        {'id': 196, 'title': 'Вяземский', 'type': LocationType.CITY},
        {'id': 197, 'title': 'Вязники', 'type': LocationType.CITY},
        {'id': 198, 'title': 'Вязьма', 'type': LocationType.CITY},
        {'id': 199, 'title': 'Вятские Поляны', 'type': LocationType.CITY},
        {'id': 200, 'title': 'Гаврилов Посад', 'type': LocationType.CITY},
        {'id': 201, 'title': 'Гаврилов-Ям', 'type': LocationType.CITY},
        {'id': 202, 'title': 'Гагарин', 'type': LocationType.CITY},
        {'id': 203, 'title': 'Гаджиево', 'type': LocationType.CITY},
        {'id': 204, 'title': 'Гай', 'type': LocationType.CITY},
        {'id': 205, 'title': 'Галич', 'type': LocationType.CITY},
        {'id': 206, 'title': 'Гатчина', 'type': LocationType.CITY},
        {'id': 207, 'title': 'Гвардейск', 'type': LocationType.CITY},
        {'id': 208, 'title': 'Гдов', 'type': LocationType.CITY},
        {'id': 209, 'title': 'Геленджик', 'type': LocationType.CITY},
        {'id': 210, 'title': 'Георгиевск', 'type': LocationType.CITY},
        {'id': 211, 'title': 'Глазов', 'type': LocationType.CITY},
        {'id': 212, 'title': 'Голицыно', 'type': LocationType.CITY},
        {'id': 213, 'title': 'Горбатов', 'type': LocationType.CITY},
        {'id': 214, 'title': 'Горно-Алтайск', 'type': LocationType.CITY},
        {'id': 215, 'title': 'Горнозаводск', 'type': LocationType.CITY},
        {'id': 216, 'title': 'Горняк', 'type': LocationType.CITY},
        {'id': 217, 'title': 'Городец', 'type': LocationType.CITY},
        {'id': 218, 'title': 'Городище', 'type': LocationType.CITY},
        {'id': 219, 'title': 'Городовиковск', 'type': LocationType.CITY},
        {'id': 220, 'title': 'Гороховец', 'type': LocationType.CITY},
        {'id': 221, 'title': 'Горячий Ключ', 'type': LocationType.CITY},
        {'id': 222, 'title': 'Грайворон', 'type': LocationType.CITY},
        {'id': 223, 'title': 'Гремячинск', 'type': LocationType.CITY},
        {'id': 224, 'title': 'Грозный', 'type': LocationType.CITY},
        {'id': 225, 'title': 'Грязи', 'type': LocationType.CITY},
        {'id': 226, 'title': 'Грязовец', 'type': LocationType.CITY},
        {'id': 227, 'title': 'Губаха', 'type': LocationType.CITY},
        {'id': 228, 'title': 'Губкин', 'type': LocationType.CITY},
        {'id': 229, 'title': 'Губкинский', 'type': LocationType.CITY},
        {'id': 230, 'title': 'Гудермес', 'type': LocationType.CITY},
        {'id': 231, 'title': 'Гуково', 'type': LocationType.CITY},
        {'id': 232, 'title': 'Гулькевичи', 'type': LocationType.CITY},
        {'id': 233, 'title': 'Гурьевск (Калининградская область)', 'type': LocationType.CITY},
        {'id': 234, 'title': 'Гурьевск (Кемеровская область)', 'type': LocationType.CITY},
        {'id': 235, 'title': 'Гусев', 'type': LocationType.CITY},
        {'id': 236, 'title': 'Гусиноозёрск', 'type': LocationType.CITY},
        {'id': 237, 'title': 'Гусь-Хрустальный', 'type': LocationType.CITY},
        {'id': 238, 'title': 'Давлеканово', 'type': LocationType.CITY},
        {'id': 239, 'title': 'Дагестанские Огни', 'type': LocationType.CITY},
        {'id': 240, 'title': 'Далматово', 'type': LocationType.CITY},
        {'id': 241, 'title': 'Дальнегорск', 'type': LocationType.CITY},
        {'id': 242, 'title': 'Дальнереченск', 'type': LocationType.CITY},
        {'id': 243, 'title': 'Данилов', 'type': LocationType.CITY},
        {'id': 244, 'title': 'Данков', 'type': LocationType.CITY},
        {'id': 245, 'title': 'Дегтярск', 'type': LocationType.CITY},
        {'id': 246, 'title': 'Дедовск', 'type': LocationType.CITY},
        {'id': 247, 'title': 'Демидов', 'type': LocationType.CITY},
        {'id': 248, 'title': 'Дербент', 'type': LocationType.CITY},
        {'id': 249, 'title': 'Десногорск', 'type': LocationType.CITY},
        {'id': 250, 'title': 'Джанкой', 'type': LocationType.CITY},
        {'id': 251, 'title': 'Дзержинск', 'type': LocationType.CITY},
        {'id': 252, 'title': 'Дзержинский', 'type': LocationType.CITY},
        {'id': 253, 'title': 'Дивногорск', 'type': LocationType.CITY},
        {'id': 254, 'title': 'Дигора', 'type': LocationType.CITY},
        {'id': 255, 'title': 'Димитровград', 'type': LocationType.CITY},
        {'id': 256, 'title': 'Дмитриев', 'type': LocationType.CITY},
        {'id': 257, 'title': 'Дмитров', 'type': LocationType.CITY},
        {'id': 258, 'title': 'Дмитровск', 'type': LocationType.CITY},
        {'id': 259, 'title': 'Дно', 'type': LocationType.CITY},
        {'id': 260, 'title': 'Добрянка', 'type': LocationType.CITY},
        {'id': 261, 'title': 'Долгопрудный', 'type': LocationType.CITY},
        {'id': 262, 'title': 'Долинск', 'type': LocationType.CITY},
        {'id': 263, 'title': 'Домодедово', 'type': LocationType.CITY},
        {'id': 264, 'title': 'Донецк', 'type': LocationType.CITY},
        {'id': 265, 'title': 'Донской', 'type': LocationType.CITY},
        {'id': 266, 'title': 'Дорогобуж', 'type': LocationType.CITY},
        {'id': 267, 'title': 'Дрезна', 'type': LocationType.CITY},
        {'id': 268, 'title': 'Дубна', 'type': LocationType.CITY},
        {'id': 269, 'title': 'Дубовка', 'type': LocationType.CITY},
        {'id': 270, 'title': 'Дудинка', 'type': LocationType.CITY},
        {'id': 271, 'title': 'Духовщина', 'type': LocationType.CITY},
        {'id': 272, 'title': 'Дюртюли', 'type': LocationType.CITY},
        {'id': 273, 'title': 'Дятьково', 'type': LocationType.CITY},
        {'id': 274, 'title': 'Евпатория', 'type': LocationType.CITY},
        {'id': 275, 'title': 'Егорьевск', 'type': LocationType.CITY},
        {'id': 276, 'title': 'Ейск', 'type': LocationType.CITY},
        {'id': 277, 'title': 'Екатеринбург', 'type': LocationType.CITY},
        {'id': 278, 'title': 'Елабуга', 'type': LocationType.CITY},
        {'id': 279, 'title': 'Елец', 'type': LocationType.CITY},
        {'id': 280, 'title': 'Елизово', 'type': LocationType.CITY},
        {'id': 281, 'title': 'Ельня', 'type': LocationType.CITY},
        {'id': 282, 'title': 'Еманжелинск', 'type': LocationType.CITY},
        {'id': 283, 'title': 'Емва', 'type': LocationType.CITY},
        {'id': 284, 'title': 'Енисейск', 'type': LocationType.CITY},
        {'id': 285, 'title': 'Ермолино', 'type': LocationType.CITY},
        {'id': 286, 'title': 'Ершов', 'type': LocationType.CITY},
        {'id': 287, 'title': 'Ессентуки', 'type': LocationType.CITY},
        {'id': 288, 'title': 'Ефремов', 'type': LocationType.CITY},
        {'id': 289, 'title': 'Железноводск', 'type': LocationType.CITY},
        {'id': 290, 'title': 'Железногорск (Красноярский край)', 'type': LocationType.CITY},
        {'id': 291, 'title': 'Железногорск (Курская область)', 'type': LocationType.CITY},
        {'id': 292, 'title': 'Железногорск-Илимский', 'type': LocationType.CITY},
        {'id': 293, 'title': 'Жердевка', 'type': LocationType.CITY},
        {'id': 294, 'title': 'Жигулёвск', 'type': LocationType.CITY},
        {'id': 295, 'title': 'Жиздра', 'type': LocationType.CITY},
        {'id': 296, 'title': 'Жирновск', 'type': LocationType.CITY},
        {'id': 297, 'title': 'Жуков', 'type': LocationType.CITY},
        {'id': 298, 'title': 'Жуковка', 'type': LocationType.CITY},
        {'id': 299, 'title': 'Жуковский', 'type': LocationType.CITY},
        {'id': 300, 'title': 'Завитинск', 'type': LocationType.CITY},
        {'id': 301, 'title': 'Заводоуковск', 'type': LocationType.CITY},
        {'id': 302, 'title': 'Заволжск', 'type': LocationType.CITY},
        {'id': 303, 'title': 'Заволжье', 'type': LocationType.CITY},
        {'id': 304, 'title': 'Задонск', 'type': LocationType.CITY},
        {'id': 305, 'title': 'Заинск', 'type': LocationType.CITY},
        {'id': 306, 'title': 'Закаменск', 'type': LocationType.CITY},
        {'id': 307, 'title': 'Заозёрный', 'type': LocationType.CITY},
        {'id': 308, 'title': 'Заозёрск', 'type': LocationType.CITY},
        {'id': 309, 'title': 'Западная Двина', 'type': LocationType.CITY},
        {'id': 310, 'title': 'Заполярный', 'type': LocationType.CITY},
        {'id': 311, 'title': 'Зарайск', 'type': LocationType.CITY},
        {'id': 312, 'title': 'Заречный (Пензенская область)', 'type': LocationType.CITY},
        {'id': 313, 'title': 'Заречный (Свердловская область)', 'type': LocationType.CITY},
        {'id': 314, 'title': 'Заринск', 'type': LocationType.CITY},
        {'id': 315, 'title': 'Звенигово', 'type': LocationType.CITY},
        {'id': 316, 'title': 'Звенигород', 'type': LocationType.CITY},
        {'id': 317, 'title': 'Зверево', 'type': LocationType.CITY},
        {'id': 318, 'title': 'Зеленогорск', 'type': LocationType.CITY},
        {'id': 319, 'title': 'Зеленоградск', 'type': LocationType.CITY},
        {'id': 320, 'title': 'Зеленодольск', 'type': LocationType.CITY},
        {'id': 321, 'title': 'Зеленокумск', 'type': LocationType.CITY},
        {'id': 322, 'title': 'Зерноград', 'type': LocationType.CITY},
        {'id': 323, 'title': 'Зея', 'type': LocationType.CITY},
        {'id': 324, 'title': 'Зима', 'type': LocationType.CITY},
        {'id': 325, 'title': 'Златоуст', 'type': LocationType.CITY},
        {'id': 326, 'title': 'Злынка', 'type': LocationType.CITY},
        {'id': 327, 'title': 'Змеиногорск', 'type': LocationType.CITY},
        {'id': 328, 'title': 'Знаменск', 'type': LocationType.CITY},
        {'id': 329, 'title': 'Зубцов', 'type': LocationType.CITY},
        {'id': 330, 'title': 'Зуевка', 'type': LocationType.CITY},
        {'id': 331, 'title': 'Ивангород', 'type': LocationType.CITY},
        {'id': 332, 'title': 'Иваново', 'type': LocationType.CITY},
        {'id': 333, 'title': 'Ивантеевка', 'type': LocationType.CITY},
        {'id': 334, 'title': 'Ивдель', 'type': LocationType.CITY},
        {'id': 335, 'title': 'Игарка', 'type': LocationType.CITY},
        {'id': 336, 'title': 'Ижевск', 'type': LocationType.CITY},
        {'id': 337, 'title': 'Избербаш', 'type': LocationType.CITY},
        {'id': 338, 'title': 'Изобильный', 'type': LocationType.CITY},
        {'id': 339, 'title': 'Иланский', 'type': LocationType.CITY},
        {'id': 340, 'title': 'Инза', 'type': LocationType.CITY},
        {'id': 341, 'title': 'Иннополис', 'type': LocationType.CITY},
        {'id': 342, 'title': 'Инсар', 'type': LocationType.CITY},
        {'id': 343, 'title': 'Инта', 'type': LocationType.CITY},
        {'id': 344, 'title': 'Ипатово', 'type': LocationType.CITY},
        {'id': 345, 'title': 'Ирбит', 'type': LocationType.CITY},
        {'id': 346, 'title': 'Иркутск', 'type': LocationType.CITY},
        {'id': 347, 'title': 'Исилькуль', 'type': LocationType.CITY},
        {'id': 348, 'title': 'Искитим', 'type': LocationType.CITY},
        {'id': 349, 'title': 'Истра', 'type': LocationType.CITY},
        {'id': 350, 'title': 'Ишим', 'type': LocationType.CITY},
        {'id': 351, 'title': 'Ишимбай', 'type': LocationType.CITY},
        {'id': 352, 'title': 'Йошкар-Ола', 'type': LocationType.CITY},
        {'id': 353, 'title': 'Кадников', 'type': LocationType.CITY},
        {'id': 354, 'title': 'Казань', 'type': LocationType.CITY},
        {'id': 355, 'title': 'Калач', 'type': LocationType.CITY},
        {'id': 356, 'title': 'Калач-на-Дону', 'type': LocationType.CITY},
        {'id': 357, 'title': 'Калачинск', 'type': LocationType.CITY},
        {'id': 358, 'title': 'Калининград', 'type': LocationType.CITY},
        {'id': 359, 'title': 'Калининск', 'type': LocationType.CITY},
        {'id': 360, 'title': 'Калтан', 'type': LocationType.CITY},
        {'id': 361, 'title': 'Калуга', 'type': LocationType.CITY},
        {'id': 362, 'title': 'Калязин', 'type': LocationType.CITY},
        {'id': 363, 'title': 'Камбарка', 'type': LocationType.CITY},
        {'id': 364, 'title': 'Каменка', 'type': LocationType.CITY},
        {'id': 365, 'title': 'Каменногорск', 'type': LocationType.CITY},
        {'id': 366, 'title': 'Каменск-Уральский', 'type': LocationType.CITY},
        {'id': 367, 'title': 'Каменск-Шахтинский', 'type': LocationType.CITY},
        {'id': 368, 'title': 'Камень-на-Оби', 'type': LocationType.CITY},
        {'id': 369, 'title': 'Камешково', 'type': LocationType.CITY},
        {'id': 370, 'title': 'Камызяк', 'type': LocationType.CITY},
        {'id': 371, 'title': 'Камышин', 'type': LocationType.CITY},
        {'id': 372, 'title': 'Камышлов', 'type': LocationType.CITY},
        {'id': 373, 'title': 'Канаш', 'type': LocationType.CITY},
        {'id': 374, 'title': 'Кандалакша', 'type': LocationType.CITY},
        {'id': 375, 'title': 'Канск', 'type': LocationType.CITY},
        {'id': 376, 'title': 'Карабаново', 'type': LocationType.CITY},
        {'id': 377, 'title': 'Карабаш', 'type': LocationType.CITY},
        {'id': 378, 'title': 'Карабулак', 'type': LocationType.CITY},
        {'id': 379, 'title': 'Карасук', 'type': LocationType.CITY},
        {'id': 380, 'title': 'Карачаевск', 'type': LocationType.CITY},
        {'id': 381, 'title': 'Карачев', 'type': LocationType.CITY},
        {'id': 382, 'title': 'Каргат', 'type': LocationType.CITY},
        {'id': 383, 'title': 'Каргополь', 'type': LocationType.CITY},
        {'id': 384, 'title': 'Карпинск', 'type': LocationType.CITY},
        {'id': 385, 'title': 'Карталы', 'type': LocationType.CITY},
        {'id': 386, 'title': 'Касимов', 'type': LocationType.CITY},
        {'id': 387, 'title': 'Касли', 'type': LocationType.CITY},
        {'id': 388, 'title': 'Каспийск', 'type': LocationType.CITY},
        {'id': 389, 'title': 'Катав-Ивановск', 'type': LocationType.CITY},
        {'id': 390, 'title': 'Катайск', 'type': LocationType.CITY},
        {'id': 391, 'title': 'Качканар', 'type': LocationType.CITY},
        {'id': 392, 'title': 'Кашин', 'type': LocationType.CITY},
        {'id': 393, 'title': 'Кашира', 'type': LocationType.CITY},
        {'id': 394, 'title': 'Кедровый', 'type': LocationType.CITY},
        {'id': 395, 'title': 'Кемерово', 'type': LocationType.CITY},
        {'id': 396, 'title': 'Кемь', 'type': LocationType.CITY},
        {'id': 397, 'title': 'Керчь', 'type': LocationType.CITY},
        {'id': 398, 'title': 'Кизел', 'type': LocationType.CITY},
        {'id': 399, 'title': 'Кизилюрт', 'type': LocationType.CITY},
        {'id': 400, 'title': 'Кизляр', 'type': LocationType.CITY},
        {'id': 401, 'title': 'Кимовск', 'type': LocationType.CITY},
        {'id': 402, 'title': 'Кимры', 'type': LocationType.CITY},
        {'id': 403, 'title': 'Кингисепп', 'type': LocationType.CITY},
        {'id': 404, 'title': 'Кинель', 'type': LocationType.CITY},
        {'id': 405, 'title': 'Кинешма', 'type': LocationType.CITY},
        {'id': 406, 'title': 'Киреевск', 'type': LocationType.CITY},
        {'id': 407, 'title': 'Киренск', 'type': LocationType.CITY},
        {'id': 408, 'title': 'Киржач', 'type': LocationType.CITY},
        {'id': 409, 'title': 'Кириллов', 'type': LocationType.CITY},
        {'id': 410, 'title': 'Кириши', 'type': LocationType.CITY},
        {'id': 411, 'title': 'Киров (Калужская область)', 'type': LocationType.CITY},
        {'id': 412, 'title': 'Киров (Кировская область)', 'type': LocationType.CITY},
        {'id': 413, 'title': 'Кировград', 'type': LocationType.CITY},
        {'id': 414, 'title': 'Кирово-Чепецк', 'type': LocationType.CITY},
        {'id': 415, 'title': 'Кировск (Ленинградская область)', 'type': LocationType.CITY},
        {'id': 416, 'title': 'Кировск (Мурманская область)', 'type': LocationType.CITY},
        {'id': 417, 'title': 'Кирс', 'type': LocationType.CITY},
        {'id': 418, 'title': 'Кирсанов', 'type': LocationType.CITY},
        {'id': 419, 'title': 'Киселёвск', 'type': LocationType.CITY},
        {'id': 420, 'title': 'Кисловодск', 'type': LocationType.CITY},
        {'id': 421, 'title': 'Клин', 'type': LocationType.CITY},
        {'id': 422, 'title': 'Клинцы', 'type': LocationType.CITY},
        {'id': 423, 'title': 'Княгинино', 'type': LocationType.CITY},
        {'id': 424, 'title': 'Ковдор', 'type': LocationType.CITY},
        {'id': 425, 'title': 'Ковров', 'type': LocationType.CITY},
        {'id': 426, 'title': 'Ковылкино', 'type': LocationType.CITY},
        {'id': 427, 'title': 'Когалым', 'type': LocationType.CITY},
        {'id': 428, 'title': 'Кодинск', 'type': LocationType.CITY},
        {'id': 429, 'title': 'Козельск', 'type': LocationType.CITY},
        {'id': 430, 'title': 'Козловка', 'type': LocationType.CITY},
        {'id': 431, 'title': 'Козьмодемьянск', 'type': LocationType.CITY},
        {'id': 432, 'title': 'Кола', 'type': LocationType.CITY},
        {'id': 433, 'title': 'Кологрив', 'type': LocationType.CITY},
        {'id': 434, 'title': 'Коломна', 'type': LocationType.CITY},
        {'id': 435, 'title': 'Колпашево', 'type': LocationType.CITY},
        {'id': 436, 'title': 'Колтуши', 'type': LocationType.CITY},
        {'id': 437, 'title': 'Кольчугино', 'type': LocationType.CITY},
        {'id': 438, 'title': 'Коммунар', 'type': LocationType.CITY},
        {'id': 439, 'title': 'Комсомольск', 'type': LocationType.CITY},
        {'id': 440, 'title': 'Комсомольск-на-Амуре', 'type': LocationType.CITY},
        {'id': 441, 'title': 'Конаково', 'type': LocationType.CITY},
        {'id': 442, 'title': 'Кондопога', 'type': LocationType.CITY},
        {'id': 443, 'title': 'Кондрово', 'type': LocationType.CITY},
        {'id': 444, 'title': 'Константиновск', 'type': LocationType.CITY},
        {'id': 445, 'title': 'Копейск', 'type': LocationType.CITY},
        {'id': 446, 'title': 'Кораблино', 'type': LocationType.CITY},
        {'id': 447, 'title': 'Кореновск', 'type': LocationType.CITY},
        {'id': 448, 'title': 'Коркино', 'type': LocationType.CITY},
        {'id': 449, 'title': 'Королёв', 'type': LocationType.CITY},
        {'id': 450, 'title': 'Короча', 'type': LocationType.CITY},
        {'id': 451, 'title': 'Корсаков', 'type': LocationType.CITY},
        {'id': 452, 'title': 'Коряжма', 'type': LocationType.CITY},
        {'id': 453, 'title': 'Костерёво', 'type': LocationType.CITY},
        {'id': 454, 'title': 'Костомукша', 'type': LocationType.CITY},
        {'id': 455, 'title': 'Кострома', 'type': LocationType.CITY},
        {'id': 456, 'title': 'Котельники', 'type': LocationType.CITY},
        {'id': 457, 'title': 'Котельниково', 'type': LocationType.CITY},
        {'id': 458, 'title': 'Котельнич', 'type': LocationType.CITY},
        {'id': 459, 'title': 'Котлас', 'type': LocationType.CITY},
        {'id': 460, 'title': 'Котово', 'type': LocationType.CITY},
        {'id': 461, 'title': 'Котовск', 'type': LocationType.CITY},
        {'id': 462, 'title': 'Кохма', 'type': LocationType.CITY},
        {'id': 463, 'title': 'Красавино', 'type': LocationType.CITY},
        {'id': 464, 'title': 'Красноармейск (Московская область)', 'type': LocationType.CITY},
        {'id': 465, 'title': 'Красноармейск (Саратовская область)', 'type': LocationType.CITY},
        {'id': 466, 'title': 'Красновишерск', 'type': LocationType.CITY},
        {'id': 467, 'title': 'Красногорск', 'type': LocationType.CITY},
        {'id': 468, 'title': 'Краснодар', 'type': LocationType.CITY},
        {'id': 469, 'title': 'Краснозаводск', 'type': LocationType.CITY},
        {'id': 470, 'title': 'Краснознаменск (Калининградская область)', 'type': LocationType.CITY},
        {'id': 471, 'title': 'Краснознаменск (Московская область)', 'type': LocationType.CITY},
        {'id': 472, 'title': 'Краснокаменск', 'type': LocationType.CITY},
        {'id': 473, 'title': 'Краснокамск', 'type': LocationType.CITY},
        {'id': 474, 'title': 'Красноперекопск', 'type': LocationType.CITY},
        {'id': 475, 'title': 'Краснослободск (Волгоградская область)', 'type': LocationType.CITY},
        {'id': 476, 'title': 'Краснослободск (Мордовия)', 'type': LocationType.CITY},
        {'id': 477, 'title': 'Краснотурьинск', 'type': LocationType.CITY},
        {'id': 478, 'title': 'Красноуральск', 'type': LocationType.CITY},
        {'id': 479, 'title': 'Красноуфимск', 'type': LocationType.CITY},
        {'id': 480, 'title': 'Красноярск', 'type': LocationType.CITY},
        {'id': 481, 'title': 'Красный Кут', 'type': LocationType.CITY},
        {'id': 482, 'title': 'Красный Сулин', 'type': LocationType.CITY},
        {'id': 483, 'title': 'Красный Холм', 'type': LocationType.CITY},
        {'id': 484, 'title': 'Кремёнки', 'type': LocationType.CITY},
        {'id': 485, 'title': 'Кропоткин', 'type': LocationType.CITY},
        {'id': 486, 'title': 'Крымск', 'type': LocationType.CITY},
        {'id': 487, 'title': 'Кстово', 'type': LocationType.CITY},
        {'id': 488, 'title': 'Кубинка', 'type': LocationType.CITY},
        {'id': 489, 'title': 'Кувандык', 'type': LocationType.CITY},
        {'id': 490, 'title': 'Кувшиново', 'type': LocationType.CITY},
        {'id': 491, 'title': 'Кудрово', 'type': LocationType.CITY},
        {'id': 492, 'title': 'Кудымкар', 'type': LocationType.CITY},
        {'id': 493, 'title': 'Кузнецк', 'type': LocationType.CITY},
        {'id': 494, 'title': 'Куйбышев', 'type': LocationType.CITY},
        {'id': 495, 'title': 'Кукмор', 'type': LocationType.CITY},
        {'id': 496, 'title': 'Кулебаки', 'type': LocationType.CITY},
        {'id': 497, 'title': 'Кумертау', 'type': LocationType.CITY},
        {'id': 498, 'title': 'Кунгур', 'type': LocationType.CITY},
        {'id': 499, 'title': 'Купино', 'type': LocationType.CITY},
        {'id': 500, 'title': 'Курган', 'type': LocationType.CITY},
        {'id': 501, 'title': 'Курганинск', 'type': LocationType.CITY},
        {'id': 502, 'title': 'Курильск', 'type': LocationType.CITY},
        {'id': 503, 'title': 'Курлово', 'type': LocationType.CITY},
        {'id': 504, 'title': 'Куровское', 'type': LocationType.CITY},
        {'id': 505, 'title': 'Курск', 'type': LocationType.CITY},
        {'id': 506, 'title': 'Куртамыш', 'type': LocationType.CITY},
        {'id': 507, 'title': 'Курчалой', 'type': LocationType.CITY},
        {'id': 508, 'title': 'Курчатов', 'type': LocationType.CITY},
        {'id': 509, 'title': 'Куса', 'type': LocationType.CITY},
        {'id': 510, 'title': 'Кушва', 'type': LocationType.CITY},
        {'id': 511, 'title': 'Кызыл', 'type': LocationType.CITY},
        {'id': 512, 'title': 'Кыштым', 'type': LocationType.CITY},
        {'id': 513, 'title': 'Кяхта', 'type': LocationType.CITY},
        {'id': 514, 'title': 'Лабинск', 'type': LocationType.CITY},
        {'id': 515, 'title': 'Лабытнанги', 'type': LocationType.CITY},
        {'id': 516, 'title': 'Лагань', 'type': LocationType.CITY},
        {'id': 517, 'title': 'Ладушкин', 'type': LocationType.CITY},
        {'id': 518, 'title': 'Лаишево', 'type': LocationType.CITY},
        {'id': 519, 'title': 'Лакинск', 'type': LocationType.CITY},
        {'id': 520, 'title': 'Лангепас', 'type': LocationType.CITY},
        {'id': 521, 'title': 'Лахденпохья', 'type': LocationType.CITY},
        {'id': 522, 'title': 'Лебедянь', 'type': LocationType.CITY},
        {'id': 523, 'title': 'Лениногорск', 'type': LocationType.CITY},
        {'id': 524, 'title': 'Ленинск', 'type': LocationType.CITY},
        {'id': 525, 'title': 'Ленинск-Кузнецкий', 'type': LocationType.CITY},
        {'id': 526, 'title': 'Ленск', 'type': LocationType.CITY},
        {'id': 527, 'title': 'Лермонтов', 'type': LocationType.CITY},
        {'id': 528, 'title': 'Лесной', 'type': LocationType.CITY},
        {'id': 529, 'title': 'Лесозаводск', 'type': LocationType.CITY},
        {'id': 530, 'title': 'Лесосибирск', 'type': LocationType.CITY},
        {'id': 531, 'title': 'Ливны', 'type': LocationType.CITY},
        {'id': 532, 'title': 'Ликино-Дулёво', 'type': LocationType.CITY},
        {'id': 533, 'title': 'Липецк', 'type': LocationType.CITY},
        {'id': 534, 'title': 'Липки', 'type': LocationType.CITY},
        {'id': 535, 'title': 'Лиски', 'type': LocationType.CITY},
        {'id': 536, 'title': 'Лихославль', 'type': LocationType.CITY},
        {'id': 537, 'title': 'Лобня', 'type': LocationType.CITY},
        {'id': 538, 'title': 'Лодейное Поле', 'type': LocationType.CITY},
        {'id': 539, 'title': 'Лосино-Петровский', 'type': LocationType.CITY},
        {'id': 540, 'title': 'Луга', 'type': LocationType.CITY},
        {'id': 541, 'title': 'Луза', 'type': LocationType.CITY},
        {'id': 542, 'title': 'Лукоянов', 'type': LocationType.CITY},
        {'id': 543, 'title': 'Луховицы', 'type': LocationType.CITY},
        {'id': 544, 'title': 'Лысково', 'type': LocationType.CITY},
        {'id': 545, 'title': 'Лысьва', 'type': LocationType.CITY},
        {'id': 546, 'title': 'Лыткарино', 'type': LocationType.CITY},
        {'id': 547, 'title': 'Льгов', 'type': LocationType.CITY},
        {'id': 548, 'title': 'Любань', 'type': LocationType.CITY},
        {'id': 549, 'title': 'Люберцы', 'type': LocationType.CITY},
        {'id': 550, 'title': 'Любим', 'type': LocationType.CITY},
        {'id': 551, 'title': 'Людиново', 'type': LocationType.CITY},
        {'id': 552, 'title': 'Лянтор', 'type': LocationType.CITY},
        {'id': 553, 'title': 'Магадан', 'type': LocationType.CITY},
        {'id': 554, 'title': 'Магас', 'type': LocationType.CITY},
        {'id': 555, 'title': 'Магнитогорск', 'type': LocationType.CITY},
        {'id': 556, 'title': 'Майкоп', 'type': LocationType.CITY},
        {'id': 557, 'title': 'Майский', 'type': LocationType.CITY},
        {'id': 558, 'title': 'Макаров', 'type': LocationType.CITY},
        {'id': 559, 'title': 'Макарьев', 'type': LocationType.CITY},
        {'id': 560, 'title': 'Макушино', 'type': LocationType.CITY},
        {'id': 561, 'title': 'Малая Вишера', 'type': LocationType.CITY},
        {'id': 562, 'title': 'Малгобек', 'type': LocationType.CITY},
        {'id': 563, 'title': 'Малмыж', 'type': LocationType.CITY},
        {'id': 564, 'title': 'Малоархангельск', 'type': LocationType.CITY},
        {'id': 565, 'title': 'Малоярославец', 'type': LocationType.CITY},
        {'id': 566, 'title': 'Мамадыш', 'type': LocationType.CITY},
        {'id': 567, 'title': 'Мамоново', 'type': LocationType.CITY},
        {'id': 568, 'title': 'Мантурово', 'type': LocationType.CITY},
        {'id': 569, 'title': 'Мариинск', 'type': LocationType.CITY},
        {'id': 570, 'title': 'Мариинский Посад', 'type': LocationType.CITY},
        {'id': 571, 'title': 'Маркс', 'type': LocationType.CITY},
        {'id': 572, 'title': 'Махачкала', 'type': LocationType.CITY},
        {'id': 573, 'title': 'Мглин', 'type': LocationType.CITY},
        {'id': 574, 'title': 'Мегион', 'type': LocationType.CITY},
        {'id': 575, 'title': 'Медвежьегорск', 'type': LocationType.CITY},
        {'id': 576, 'title': 'Медногорск', 'type': LocationType.CITY},
        {'id': 577, 'title': 'Медынь', 'type': LocationType.CITY},
        {'id': 578, 'title': 'Межгорье', 'type': LocationType.CITY},
        {'id': 579, 'title': 'Междуреченск', 'type': LocationType.CITY},
        {'id': 580, 'title': 'Мезень', 'type': LocationType.CITY},
        {'id': 581, 'title': 'Меленки', 'type': LocationType.CITY},
        {'id': 582, 'title': 'Мелеуз', 'type': LocationType.CITY},
        {'id': 583, 'title': 'Менделеевск', 'type': LocationType.CITY},
        {'id': 584, 'title': 'Мензелинск', 'type': LocationType.CITY},
        {'id': 585, 'title': 'Мещовск', 'type': LocationType.CITY},
        {'id': 586, 'title': 'Миасс', 'type': LocationType.CITY},
        {'id': 587, 'title': 'Микунь', 'type': LocationType.CITY},
        {'id': 588, 'title': 'Миллерово', 'type': LocationType.CITY},
        {'id': 589, 'title': 'Минеральные Воды', 'type': LocationType.CITY},
        {'id': 590, 'title': 'Минусинск', 'type': LocationType.CITY},
        {'id': 591, 'title': 'Миньяр', 'type': LocationType.CITY},
        {'id': 592, 'title': 'Мирный (Якутия)', 'type': LocationType.CITY},
        {'id': 593, 'title': 'Мирный (Архангельская область)', 'type': LocationType.CITY},
        {'id': 594, 'title': 'Михайлов', 'type': LocationType.CITY},
        {'id': 595, 'title': 'Михайловка', 'type': LocationType.CITY},
        {'id': 596, 'title': 'Михайловск (Свердловская область)', 'type': LocationType.CITY},
        {'id': 597, 'title': 'Михайловск (Ставропольский край)', 'type': LocationType.CITY},
        {'id': 598, 'title': 'Мичуринск', 'type': LocationType.CITY},
        {'id': 599, 'title': 'Могоча', 'type': LocationType.CITY},
        {'id': 600, 'title': 'Можайск', 'type': LocationType.CITY},
        {'id': 601, 'title': 'Можга', 'type': LocationType.CITY},
        {'id': 602, 'title': 'Моздок', 'type': LocationType.CITY},
        {'id': 603, 'title': 'Мончегорск', 'type': LocationType.CITY},
        {'id': 604, 'title': 'Морозовск', 'type': LocationType.CITY},
        {'id': 605, 'title': 'Моршанск', 'type': LocationType.CITY},
        {'id': 606, 'title': 'Мосальск', 'type': LocationType.CITY},
        {'id': 607, 'title': 'Москва', 'type': LocationType.CITY},
        {'id': 608, 'title': 'Муравленко', 'type': LocationType.CITY},
        {'id': 609, 'title': 'Мураши', 'type': LocationType.CITY},
        {'id': 610, 'title': 'Мурино', 'type': LocationType.CITY},
        {'id': 611, 'title': 'Мурманск', 'type': LocationType.CITY},
        {'id': 612, 'title': 'Муром', 'type': LocationType.CITY},
        {'id': 613, 'title': 'Мценск', 'type': LocationType.CITY},
        {'id': 614, 'title': 'Мыски', 'type': LocationType.CITY},
        {'id': 615, 'title': 'Мытищи', 'type': LocationType.CITY},
        {'id': 616, 'title': 'Мышкин', 'type': LocationType.CITY},
        {'id': 617, 'title': 'Набережные Челны', 'type': LocationType.CITY},
        {'id': 618, 'title': 'Навашино', 'type': LocationType.CITY},
        {'id': 619, 'title': 'Наволоки', 'type': LocationType.CITY},
        {'id': 620, 'title': 'Надым', 'type': LocationType.CITY},
        {'id': 621, 'title': 'Назарово', 'type': LocationType.CITY},
        {'id': 622, 'title': 'Назрань', 'type': LocationType.CITY},
        {'id': 623, 'title': 'Называевск', 'type': LocationType.CITY},
        {'id': 624, 'title': 'Нальчик', 'type': LocationType.CITY},
        {'id': 625, 'title': 'Нариманов', 'type': LocationType.CITY},
        {'id': 626, 'title': 'Наро-Фоминск', 'type': LocationType.CITY},
        {'id': 627, 'title': 'Нарткала', 'type': LocationType.CITY},
        {'id': 628, 'title': 'Нарьян-Мар', 'type': LocationType.CITY},
        {'id': 629, 'title': 'Находка', 'type': LocationType.CITY},
        {'id': 630, 'title': 'Невель', 'type': LocationType.CITY},
        {'id': 631, 'title': 'Невельск', 'type': LocationType.CITY},
        {'id': 632, 'title': 'Невинномысск', 'type': LocationType.CITY},
        {'id': 633, 'title': 'Невьянск', 'type': LocationType.CITY},
        {'id': 634, 'title': 'Нелидово', 'type': LocationType.CITY},
        {'id': 635, 'title': 'Неман', 'type': LocationType.CITY},
        {'id': 636, 'title': 'Нерехта', 'type': LocationType.CITY},
        {'id': 637, 'title': 'Нерчинск', 'type': LocationType.CITY},
        {'id': 638, 'title': 'Нерюнгри', 'type': LocationType.CITY},
        {'id': 639, 'title': 'Нестеров', 'type': LocationType.CITY},
        {'id': 640, 'title': 'Нефтегорск', 'type': LocationType.CITY},
        {'id': 641, 'title': 'Нефтекамск', 'type': LocationType.CITY},
        {'id': 642, 'title': 'Нефтекумск', 'type': LocationType.CITY},
        {'id': 643, 'title': 'Нефтеюганск', 'type': LocationType.CITY},
        {'id': 644, 'title': 'Нея', 'type': LocationType.CITY},
        {'id': 645, 'title': 'Нижневартовск', 'type': LocationType.CITY},
        {'id': 646, 'title': 'Нижнекамск', 'type': LocationType.CITY},
        {'id': 647, 'title': 'Нижнеудинск', 'type': LocationType.CITY},
        {'id': 648, 'title': 'Нижние Серги', 'type': LocationType.CITY},
        {'id': 649, 'title': 'Нижний Ломов', 'type': LocationType.CITY},
        {'id': 650, 'title': 'Нижний Новгород', 'type': LocationType.CITY},
        {'id': 651, 'title': 'Нижний Тагил', 'type': LocationType.CITY},
        {'id': 652, 'title': 'Нижняя Салда', 'type': LocationType.CITY},
        {'id': 653, 'title': 'Нижняя Тура', 'type': LocationType.CITY},
        {'id': 654, 'title': 'Николаевск', 'type': LocationType.CITY},
        {'id': 655, 'title': 'Николаевск-на-Амуре', 'type': LocationType.CITY},
        {'id': 656, 'title': 'Никольск (Вологодская область)', 'type': LocationType.CITY},
        {'id': 657, 'title': 'Никольск (Пензенская область)', 'type': LocationType.CITY},
        {'id': 658, 'title': 'Никольское', 'type': LocationType.CITY},
        {'id': 659, 'title': 'Новая Ладога', 'type': LocationType.CITY},
        {'id': 660, 'title': 'Новая Ляля', 'type': LocationType.CITY},
        {'id': 661, 'title': 'Новоалександровск', 'type': LocationType.CITY},
        {'id': 662, 'title': 'Новоалтайск', 'type': LocationType.CITY},
        {'id': 663, 'title': 'Новоаннинский', 'type': LocationType.CITY},
        {'id': 664, 'title': 'Нововоронеж', 'type': LocationType.CITY},
        {'id': 665, 'title': 'Новодвинск', 'type': LocationType.CITY},
        {'id': 666, 'title': 'Новозыбков', 'type': LocationType.CITY},
        {'id': 667, 'title': 'Новокубанск', 'type': LocationType.CITY},
        {'id': 668, 'title': 'Новокузнецк', 'type': LocationType.CITY},
        {'id': 669, 'title': 'Новокуйбышевск', 'type': LocationType.CITY},
        {'id': 670, 'title': 'Новомичуринск', 'type': LocationType.CITY},
        {'id': 671, 'title': 'Новомосковск', 'type': LocationType.CITY},
        {'id': 672, 'title': 'Новопавловск', 'type': LocationType.CITY},
        {'id': 673, 'title': 'Новоржев', 'type': LocationType.CITY},
        {'id': 674, 'title': 'Новороссийск', 'type': LocationType.CITY},
        {'id': 675, 'title': 'Новосибирск', 'type': LocationType.CITY},
        {'id': 676, 'title': 'Новосиль', 'type': LocationType.CITY},
        {'id': 677, 'title': 'Новосокольники', 'type': LocationType.CITY},
        {'id': 678, 'title': 'Новотроицк', 'type': LocationType.CITY},
        {'id': 679, 'title': 'Новоузенск', 'type': LocationType.CITY},
        {'id': 680, 'title': 'Новоульяновск', 'type': LocationType.CITY},
        {'id': 681, 'title': 'Новоуральск', 'type': LocationType.CITY},
        {'id': 682, 'title': 'Новохопёрск', 'type': LocationType.CITY},
        {'id': 683, 'title': 'Новочебоксарск', 'type': LocationType.CITY},
        {'id': 684, 'title': 'Новочеркасск', 'type': LocationType.CITY},
        {'id': 685, 'title': 'Новошахтинск', 'type': LocationType.CITY},
        {'id': 686, 'title': 'Новый Оскол', 'type': LocationType.CITY},
        {'id': 687, 'title': 'Новый Уренгой', 'type': LocationType.CITY},
        {'id': 688, 'title': 'Ногинск', 'type': LocationType.CITY},
        {'id': 689, 'title': 'Нолинск', 'type': LocationType.CITY},
        {'id': 690, 'title': 'Норильск', 'type': LocationType.CITY},
        {'id': 691, 'title': 'Ноябрьск', 'type': LocationType.CITY},
        {'id': 692, 'title': 'Нурлат', 'type': LocationType.CITY},
        {'id': 693, 'title': 'Нытва', 'type': LocationType.CITY},
        {'id': 694, 'title': 'Нюрба', 'type': LocationType.CITY},
        {'id': 695, 'title': 'Нягань', 'type': LocationType.CITY},
        {'id': 696, 'title': 'Нязепетровск', 'type': LocationType.CITY},
        {'id': 697, 'title': 'Няндома', 'type': LocationType.CITY},
        {'id': 698, 'title': 'Облучье', 'type': LocationType.CITY},
        {'id': 699, 'title': 'Обнинск', 'type': LocationType.CITY},
        {'id': 700, 'title': 'Обоянь', 'type': LocationType.CITY},
        {'id': 701, 'title': 'Обь', 'type': LocationType.CITY},
        {'id': 702, 'title': 'Одинцово', 'type': LocationType.CITY},
        {'id': 703, 'title': 'Озёрск (Калининградская область)', 'type': LocationType.CITY},
        {'id': 704, 'title': 'Озёрск (Челябинская область)', 'type': LocationType.CITY},
        {'id': 705, 'title': 'Озёры', 'type': LocationType.CITY},
        {'id': 706, 'title': 'Октябрьск', 'type': LocationType.CITY},
        {'id': 707, 'title': 'Октябрьский', 'type': LocationType.CITY},
        {'id': 708, 'title': 'Окуловка', 'type': LocationType.CITY},
        {'id': 709, 'title': 'Олёкминск', 'type': LocationType.CITY},
        {'id': 710, 'title': 'Оленегорск', 'type': LocationType.CITY},
        {'id': 711, 'title': 'Олонец', 'type': LocationType.CITY},
        {'id': 712, 'title': 'Омск', 'type': LocationType.CITY},
        {'id': 713, 'title': 'Омутнинск', 'type': LocationType.CITY},
        {'id': 714, 'title': 'Онега', 'type': LocationType.CITY},
        {'id': 715, 'title': 'Опочка', 'type': LocationType.CITY},
        {'id': 716, 'title': 'Орёл', 'type': LocationType.CITY},
        {'id': 717, 'title': 'Оренбург', 'type': LocationType.CITY},
        {'id': 718, 'title': 'Орехово-Зуево', 'type': LocationType.CITY},
        {'id': 719, 'title': 'Орлов', 'type': LocationType.CITY},
        {'id': 720, 'title': 'Орск', 'type': LocationType.CITY},
        {'id': 721, 'title': 'Оса', 'type': LocationType.CITY},
        {'id': 722, 'title': 'Осинники', 'type': LocationType.CITY},
        {'id': 723, 'title': 'Осташков', 'type': LocationType.CITY},
        {'id': 724, 'title': 'Остров', 'type': LocationType.CITY},
        {'id': 725, 'title': 'Островной', 'type': LocationType.CITY},
        {'id': 726, 'title': 'Острогожск', 'type': LocationType.CITY},
        {'id': 727, 'title': 'Отрадное', 'type': LocationType.CITY},
        {'id': 728, 'title': 'Отрадный', 'type': LocationType.CITY},
        {'id': 729, 'title': 'Оха', 'type': LocationType.CITY},
        {'id': 730, 'title': 'Оханск', 'type': LocationType.CITY},
        {'id': 731, 'title': 'Очёр', 'type': LocationType.CITY},
        {'id': 732, 'title': 'Павлово', 'type': LocationType.CITY},
        {'id': 733, 'title': 'Павловск', 'type': LocationType.CITY},
        {'id': 734, 'title': 'Павловский Посад', 'type': LocationType.CITY},
        {'id': 735, 'title': 'Палласовка', 'type': LocationType.CITY},
        {'id': 736, 'title': 'Партизанск', 'type': LocationType.CITY},
        {'id': 737, 'title': 'Певек', 'type': LocationType.CITY},
        {'id': 738, 'title': 'Пенза', 'type': LocationType.CITY},
        {'id': 739, 'title': 'Первомайск', 'type': LocationType.CITY},
        {'id': 740, 'title': 'Первоуральск', 'type': LocationType.CITY},
        {'id': 741, 'title': 'Перевоз', 'type': LocationType.CITY},
        {'id': 742, 'title': 'Пересвет', 'type': LocationType.CITY},
        {'id': 743, 'title': 'Переславль-Залесский', 'type': LocationType.CITY},
        {'id': 744, 'title': 'Пермь', 'type': LocationType.CITY},
        {'id': 745, 'title': 'Пестово', 'type': LocationType.CITY},
        {'id': 746, 'title': 'Петров Вал', 'type': LocationType.CITY},
        {'id': 747, 'title': 'Петровск', 'type': LocationType.CITY},
        {'id': 748, 'title': 'Петровск-Забайкальский', 'type': LocationType.CITY},
        {'id': 749, 'title': 'Петрозаводск', 'type': LocationType.CITY},
        {'id': 750, 'title': 'Петропавловск-Камчатский', 'type': LocationType.CITY},
        {'id': 751, 'title': 'Петухово', 'type': LocationType.CITY},
        {'id': 752, 'title': 'Петушки', 'type': LocationType.CITY},
        {'id': 753, 'title': 'Печора', 'type': LocationType.CITY},
        {'id': 754, 'title': 'Печоры', 'type': LocationType.CITY},
        {'id': 755, 'title': 'Пикалёво', 'type': LocationType.CITY},
        {'id': 756, 'title': 'Пионерский', 'type': LocationType.CITY},
        {'id': 757, 'title': 'Питкяранта', 'type': LocationType.CITY},
        {'id': 758, 'title': 'Плавск', 'type': LocationType.CITY},
        {'id': 759, 'title': 'Пласт', 'type': LocationType.CITY},
        {'id': 760, 'title': 'Плёс', 'type': LocationType.CITY},
        {'id': 761, 'title': 'Поворино', 'type': LocationType.CITY},
        {'id': 762, 'title': 'Подольск', 'type': LocationType.CITY},
        {'id': 763, 'title': 'Подпорожье', 'type': LocationType.CITY},
        {'id': 764, 'title': 'Покачи', 'type': LocationType.CITY},
        {'id': 765, 'title': 'Покров', 'type': LocationType.CITY},
        {'id': 766, 'title': 'Покровск', 'type': LocationType.CITY},
        {'id': 767, 'title': 'Полевской', 'type': LocationType.CITY},
        {'id': 768, 'title': 'Полесск', 'type': LocationType.CITY},
        {'id': 769, 'title': 'Полысаево', 'type': LocationType.CITY},
        {'id': 770, 'title': 'Полярные Зори', 'type': LocationType.CITY},
        {'id': 771, 'title': 'Полярный', 'type': LocationType.CITY},
        {'id': 772, 'title': 'Поронайск', 'type': LocationType.CITY},
        {'id': 773, 'title': 'Порхов', 'type': LocationType.CITY},
        {'id': 774, 'title': 'Похвистнево', 'type': LocationType.CITY},
        {'id': 775, 'title': 'Почеп', 'type': LocationType.CITY},
        {'id': 776, 'title': 'Починок', 'type': LocationType.CITY},
        {'id': 777, 'title': 'Пошехонье', 'type': LocationType.CITY},
        {'id': 778, 'title': 'Правдинск', 'type': LocationType.CITY},
        {'id': 779, 'title': 'Приволжск', 'type': LocationType.CITY},
        {'id': 780, 'title': 'Приморск (Калининградская область)', 'type': LocationType.CITY},
        {'id': 781, 'title': 'Приморск (Ленинградская область)', 'type': LocationType.CITY},
        {'id': 782, 'title': 'Приморско-Ахтарск', 'type': LocationType.CITY},
        {'id': 783, 'title': 'Приозерск', 'type': LocationType.CITY},
        {'id': 784, 'title': 'Прокопьевск', 'type': LocationType.CITY},
        {'id': 785, 'title': 'Пролетарск', 'type': LocationType.CITY},
        {'id': 786, 'title': 'Протвино', 'type': LocationType.CITY},
        {'id': 787, 'title': 'Прохладный', 'type': LocationType.CITY},
        {'id': 788, 'title': 'Псков', 'type': LocationType.CITY},
        {'id': 789, 'title': 'Пугачёв', 'type': LocationType.CITY},
        {'id': 790, 'title': 'Пудож', 'type': LocationType.CITY},
        {'id': 791, 'title': 'Пустошка', 'type': LocationType.CITY},
        {'id': 792, 'title': 'Пучеж', 'type': LocationType.CITY},
        {'id': 793, 'title': 'Пушкино', 'type': LocationType.CITY},
        {'id': 794, 'title': 'Пущино', 'type': LocationType.CITY},
        {'id': 795, 'title': 'Пыталово', 'type': LocationType.CITY},
        {'id': 796, 'title': 'Пыть-Ях', 'type': LocationType.CITY},
        {'id': 797, 'title': 'Пятигорск', 'type': LocationType.CITY},
        {'id': 798, 'title': 'Радужный (Владимирская область)', 'type': LocationType.CITY},
        {'id': 799, 'title': 'Радужный (Ханты-Мансийский АО)', 'type': LocationType.CITY},
        {'id': 800, 'title': 'Райчихинск', 'type': LocationType.CITY},
        {'id': 801, 'title': 'Раменское', 'type': LocationType.CITY},
        {'id': 802, 'title': 'Рассказово', 'type': LocationType.CITY},
        {'id': 803, 'title': 'Ревда', 'type': LocationType.CITY},
        {'id': 804, 'title': 'Реж', 'type': LocationType.CITY},
        {'id': 805, 'title': 'Реутов', 'type': LocationType.CITY},
        {'id': 806, 'title': 'Ржев', 'type': LocationType.CITY},
        {'id': 807, 'title': 'Родники', 'type': LocationType.CITY},
        {'id': 808, 'title': 'Рославль', 'type': LocationType.CITY},
        {'id': 809, 'title': 'Россошь', 'type': LocationType.CITY},
        {'id': 810, 'title': 'Ростов-на-Дону', 'type': LocationType.CITY},
        {'id': 811, 'title': 'Ростов', 'type': LocationType.CITY},
        {'id': 812, 'title': 'Рошаль', 'type': LocationType.CITY},
        {'id': 813, 'title': 'Ртищево', 'type': LocationType.CITY},
        {'id': 814, 'title': 'Рубцовск', 'type': LocationType.CITY},
        {'id': 815, 'title': 'Рудня', 'type': LocationType.CITY},
        {'id': 816, 'title': 'Руза', 'type': LocationType.CITY},
        {'id': 817, 'title': 'Рузаевка', 'type': LocationType.CITY},
        {'id': 818, 'title': 'Рыбинск', 'type': LocationType.CITY},
        {'id': 819, 'title': 'Рыбное', 'type': LocationType.CITY},
        {'id': 820, 'title': 'Рыльск', 'type': LocationType.CITY},
        {'id': 821, 'title': 'Ряжск', 'type': LocationType.CITY},
        {'id': 822, 'title': 'Рязань', 'type': LocationType.CITY},
        {'id': 823, 'title': 'Саки', 'type': LocationType.CITY},
        {'id': 824, 'title': 'Салават', 'type': LocationType.CITY},
        {'id': 825, 'title': 'Салаир', 'type': LocationType.CITY},
        {'id': 826, 'title': 'Салехард', 'type': LocationType.CITY},
        {'id': 827, 'title': 'Сальск', 'type': LocationType.CITY},
        {'id': 828, 'title': 'Самара', 'type': LocationType.CITY},
        {'id': 829, 'title': 'Санкт-Петербург', 'type': LocationType.CITY},
        {'id': 830, 'title': 'Саранск', 'type': LocationType.CITY},
        {'id': 831, 'title': 'Сарапул', 'type': LocationType.CITY},
        {'id': 832, 'title': 'Саратов', 'type': LocationType.CITY},
        {'id': 833, 'title': 'Саров', 'type': LocationType.CITY},
        {'id': 834, 'title': 'Сасово', 'type': LocationType.CITY},
        {'id': 835, 'title': 'Сатка', 'type': LocationType.CITY},
        {'id': 836, 'title': 'Сафоново', 'type': LocationType.CITY},
        {'id': 837, 'title': 'Саяногорск', 'type': LocationType.CITY},
        {'id': 838, 'title': 'Саянск', 'type': LocationType.CITY},
        {'id': 839, 'title': 'Светлогорск', 'type': LocationType.CITY},
        {'id': 840, 'title': 'Светлоград', 'type': LocationType.CITY},
        {'id': 841, 'title': 'Светлый', 'type': LocationType.CITY},
        {'id': 842, 'title': 'Светогорск', 'type': LocationType.CITY},
        {'id': 843, 'title': 'Свирск', 'type': LocationType.CITY},
        {'id': 844, 'title': 'Свободный', 'type': LocationType.CITY},
        {'id': 845, 'title': 'Себеж', 'type': LocationType.CITY},
        {'id': 846, 'title': 'Севастополь', 'type': LocationType.CITY},
        {'id': 847, 'title': 'Северо-Курильск', 'type': LocationType.CITY},
        {'id': 848, 'title': 'Северобайкальск', 'type': LocationType.CITY},
        {'id': 849, 'title': 'Северодвинск', 'type': LocationType.CITY},
        {'id': 850, 'title': 'Североморск', 'type': LocationType.CITY},
        {'id': 851, 'title': 'Североуральск', 'type': LocationType.CITY},
        {'id': 852, 'title': 'Северск', 'type': LocationType.CITY},
        {'id': 853, 'title': 'Севск', 'type': LocationType.CITY},
        {'id': 854, 'title': 'Сегежа', 'type': LocationType.CITY},
        {'id': 855, 'title': 'Сельцо', 'type': LocationType.CITY},
        {'id': 856, 'title': 'Семёнов', 'type': LocationType.CITY},
        {'id': 857, 'title': 'Семикаракорск', 'type': LocationType.CITY},
        {'id': 858, 'title': 'Семилуки', 'type': LocationType.CITY},
        {'id': 859, 'title': 'Сенгилей', 'type': LocationType.CITY},
        {'id': 860, 'title': 'Серафимович', 'type': LocationType.CITY},
        {'id': 861, 'title': 'Сергач', 'type': LocationType.CITY},
        {'id': 862, 'title': 'Сергиев Посад', 'type': LocationType.CITY},
        {'id': 863, 'title': 'Сердобск', 'type': LocationType.CITY},
        {'id': 864, 'title': 'Серов', 'type': LocationType.CITY},
        {'id': 865, 'title': 'Серпухов', 'type': LocationType.CITY},
        {'id': 866, 'title': 'Сертолово', 'type': LocationType.CITY},
        {'id': 867, 'title': 'Сибай', 'type': LocationType.CITY},
        {'id': 868, 'title': 'Сим', 'type': LocationType.CITY},
        {'id': 869, 'title': 'Симферополь', 'type': LocationType.CITY},
        {'id': 870, 'title': 'Сковородино', 'type': LocationType.CITY},
        {'id': 871, 'title': 'Скопин', 'type': LocationType.CITY},
        {'id': 872, 'title': 'Славгород', 'type': LocationType.CITY},
        {'id': 873, 'title': 'Славск', 'type': LocationType.CITY},
        {'id': 874, 'title': 'Славянск-на-Кубани', 'type': LocationType.CITY},
        {'id': 875, 'title': 'Сланцы', 'type': LocationType.CITY},
        {'id': 876, 'title': 'Слободской', 'type': LocationType.CITY},
        {'id': 877, 'title': 'Слюдянка', 'type': LocationType.CITY},
        {'id': 878, 'title': 'Смоленск', 'type': LocationType.CITY},
        {'id': 879, 'title': 'Снежинск', 'type': LocationType.CITY},
        {'id': 880, 'title': 'Снежногорск', 'type': LocationType.CITY},
        {'id': 881, 'title': 'Собинка', 'type': LocationType.CITY},
        {'id': 882, 'title': 'Советск (Калининградская область)', 'type': LocationType.CITY},
        {'id': 883, 'title': 'Советск (Кировская область)', 'type': LocationType.CITY},
        {'id': 884, 'title': 'Советск (Тульская область)', 'type': LocationType.CITY},
        {'id': 885, 'title': 'Советская Гавань', 'type': LocationType.CITY},
        {'id': 886, 'title': 'Советский', 'type': LocationType.CITY},
        {'id': 887, 'title': 'Сокол', 'type': LocationType.CITY},
        {'id': 888, 'title': 'Солигалич', 'type': LocationType.CITY},
        {'id': 889, 'title': 'Соликамск', 'type': LocationType.CITY},
        {'id': 890, 'title': 'Солнечногорск', 'type': LocationType.CITY},
        {'id': 891, 'title': 'Соль-Илецк', 'type': LocationType.CITY},
        {'id': 892, 'title': 'Сольвычегодск', 'type': LocationType.CITY},
        {'id': 893, 'title': 'Сольцы', 'type': LocationType.CITY},
        {'id': 894, 'title': 'Сорочинск', 'type': LocationType.CITY},
        {'id': 895, 'title': 'Сорск', 'type': LocationType.CITY},
        {'id': 896, 'title': 'Сортавала', 'type': LocationType.CITY},
        {'id': 897, 'title': 'Сосенский', 'type': LocationType.CITY},
        {'id': 898, 'title': 'Сосновка', 'type': LocationType.CITY},
        {'id': 899, 'title': 'Сосновоборск', 'type': LocationType.CITY},
        {'id': 900, 'title': 'Сосновый Бор', 'type': LocationType.CITY},
        {'id': 901, 'title': 'Сосногорск', 'type': LocationType.CITY},
        {'id': 902, 'title': 'Сочи', 'type': LocationType.CITY},
        {'id': 903, 'title': 'Спас-Деменск', 'type': LocationType.CITY},
        {'id': 904, 'title': 'Спас-Клепики', 'type': LocationType.CITY},
        {'id': 905, 'title': 'Спасск', 'type': LocationType.CITY},
        {'id': 906, 'title': 'Спасск-Дальний', 'type': LocationType.CITY},
        {'id': 907, 'title': 'Спасск-Рязанский', 'type': LocationType.CITY},
        {'id': 908, 'title': 'Среднеколымск', 'type': LocationType.CITY},
        {'id': 909, 'title': 'Среднеуральск', 'type': LocationType.CITY},
        {'id': 910, 'title': 'Сретенск', 'type': LocationType.CITY},
        {'id': 911, 'title': 'Ставрополь', 'type': LocationType.CITY},
        {'id': 912, 'title': 'Старая Купавна', 'type': LocationType.CITY},
        {'id': 913, 'title': 'Старая Русса', 'type': LocationType.CITY},
        {'id': 914, 'title': 'Старица', 'type': LocationType.CITY},
        {'id': 915, 'title': 'Стародуб', 'type': LocationType.CITY},
        {'id': 916, 'title': 'Старый Крым', 'type': LocationType.CITY},
        {'id': 917, 'title': 'Старый Оскол', 'type': LocationType.CITY},
        {'id': 918, 'title': 'Стерлитамак', 'type': LocationType.CITY},
        {'id': 919, 'title': 'Стрежевой', 'type': LocationType.CITY},
        {'id': 920, 'title': 'Строитель', 'type': LocationType.CITY},
        {'id': 921, 'title': 'Струнино', 'type': LocationType.CITY},
        {'id': 922, 'title': 'Ступино', 'type': LocationType.CITY},
        {'id': 923, 'title': 'Суворов', 'type': LocationType.CITY},
        {'id': 924, 'title': 'Судак', 'type': LocationType.CITY},
        {'id': 925, 'title': 'Суджа', 'type': LocationType.CITY},
        {'id': 926, 'title': 'Судогда', 'type': LocationType.CITY},
        {'id': 927, 'title': 'Суздаль', 'type': LocationType.CITY},
        {'id': 928, 'title': 'Сунжа', 'type': LocationType.CITY},
        {'id': 929, 'title': 'Суоярви', 'type': LocationType.CITY},
        {'id': 930, 'title': 'Сураж', 'type': LocationType.CITY},
        {'id': 931, 'title': 'Сургут', 'type': LocationType.CITY},
        {'id': 932, 'title': 'Суровикино', 'type': LocationType.CITY},
        {'id': 933, 'title': 'Сурск', 'type': LocationType.CITY},
        {'id': 934, 'title': 'Сусуман', 'type': LocationType.CITY},
        {'id': 935, 'title': 'Сухиничи', 'type': LocationType.CITY},
        {'id': 936, 'title': 'Сухой Лог', 'type': LocationType.CITY},
        {'id': 937, 'title': 'Сызрань', 'type': LocationType.CITY},
        {'id': 938, 'title': 'Сыктывкар', 'type': LocationType.CITY},
        {'id': 939, 'title': 'Сысерть', 'type': LocationType.CITY},
        {'id': 940, 'title': 'Сычёвка', 'type': LocationType.CITY},
        {'id': 941, 'title': 'Сясьстрой', 'type': LocationType.CITY},
        {'id': 942, 'title': 'Тавда', 'type': LocationType.CITY},
        {'id': 943, 'title': 'Таганрог', 'type': LocationType.CITY},
        {'id': 944, 'title': 'Тайга', 'type': LocationType.CITY},
        {'id': 945, 'title': 'Тайшет', 'type': LocationType.CITY},
        {'id': 946, 'title': 'Талдом', 'type': LocationType.CITY},
        {'id': 947, 'title': 'Талица', 'type': LocationType.CITY},
        {'id': 948, 'title': 'Тамбов', 'type': LocationType.CITY},
        {'id': 949, 'title': 'Тара', 'type': LocationType.CITY},
        {'id': 950, 'title': 'Тарко-Сале', 'type': LocationType.CITY},
        {'id': 951, 'title': 'Таруса', 'type': LocationType.CITY},
        {'id': 952, 'title': 'Татарск', 'type': LocationType.CITY},
        {'id': 953, 'title': 'Таштагол', 'type': LocationType.CITY},
        {'id': 954, 'title': 'Тверь', 'type': LocationType.CITY},
        {'id': 955, 'title': 'Теберда', 'type': LocationType.CITY},
        {'id': 956, 'title': 'Тейково', 'type': LocationType.CITY},
        {'id': 957, 'title': 'Тельмана', 'type': LocationType.CITY},
        {'id': 958, 'title': 'Темников', 'type': LocationType.CITY},
        {'id': 959, 'title': 'Темрюк', 'type': LocationType.CITY},
        {'id': 960, 'title': 'Терек', 'type': LocationType.CITY},
        {'id': 961, 'title': 'Тетюши', 'type': LocationType.CITY},
        {'id': 962, 'title': 'Тимашёвск', 'type': LocationType.CITY},
        {'id': 963, 'title': 'Тихвин', 'type': LocationType.CITY},
        {'id': 964, 'title': 'Тихорецк', 'type': LocationType.CITY},
        {'id': 965, 'title': 'Тобольск', 'type': LocationType.CITY},
        {'id': 966, 'title': 'Тогучин', 'type': LocationType.CITY},
        {'id': 967, 'title': 'Тольятти', 'type': LocationType.CITY},
        {'id': 968, 'title': 'Томари', 'type': LocationType.CITY},
        {'id': 969, 'title': 'Томмот', 'type': LocationType.CITY},
        {'id': 970, 'title': 'Томск', 'type': LocationType.CITY},
        {'id': 971, 'title': 'Топки', 'type': LocationType.CITY},
        {'id': 972, 'title': 'Торжок', 'type': LocationType.CITY},
        {'id': 973, 'title': 'Торопец', 'type': LocationType.CITY},
        {'id': 974, 'title': 'Тосно', 'type': LocationType.CITY},
        {'id': 975, 'title': 'Тотьма', 'type': LocationType.CITY},
        {'id': 976, 'title': 'Трёхгорный', 'type': LocationType.CITY},
        {'id': 977, 'title': 'Троицк', 'type': LocationType.CITY},
        {'id': 978, 'title': 'Трубчевск', 'type': LocationType.CITY},
        {'id': 979, 'title': 'Туапсе', 'type': LocationType.CITY},
        {'id': 980, 'title': 'Туймазы', 'type': LocationType.CITY},
        {'id': 981, 'title': 'Тула', 'type': LocationType.CITY},
        {'id': 982, 'title': 'Тулун', 'type': LocationType.CITY},
        {'id': 983, 'title': 'Туран', 'type': LocationType.CITY},
        {'id': 984, 'title': 'Туринск', 'type': LocationType.CITY},
        {'id': 985, 'title': 'Тутаев', 'type': LocationType.CITY},
        {'id': 986, 'title': 'Тында', 'type': LocationType.CITY},
        {'id': 987, 'title': 'Тырныауз', 'type': LocationType.CITY},
        {'id': 988, 'title': 'Тюкалинск', 'type': LocationType.CITY},
        {'id': 989, 'title': 'Тюмень', 'type': LocationType.CITY},
        {'id': 990, 'title': 'Уварово', 'type': LocationType.CITY},
        {'id': 991, 'title': 'Углегорск', 'type': LocationType.CITY},
        {'id': 992, 'title': 'Углич', 'type': LocationType.CITY},
        {'id': 993, 'title': 'Удачный', 'type': LocationType.CITY},
        {'id': 994, 'title': 'Удомля', 'type': LocationType.CITY},
        {'id': 995, 'title': 'Ужур', 'type': LocationType.CITY},
        {'id': 996, 'title': 'Узловая', 'type': LocationType.CITY},
        {'id': 997, 'title': 'Улан-Удэ', 'type': LocationType.CITY},
        {'id': 998, 'title': 'Ульяновск', 'type': LocationType.CITY},
        {'id': 999, 'title': 'Унеча', 'type': LocationType.CITY},
        {'id': 1000, 'title': 'Урай', 'type': LocationType.CITY},
        {'id': 1001, 'title': 'Урень', 'type': LocationType.CITY},
        {'id': 1002, 'title': 'Уржум', 'type': LocationType.CITY},
        {'id': 1003, 'title': 'Урус-Мартан', 'type': LocationType.CITY},
        {'id': 1004, 'title': 'Урюпинск', 'type': LocationType.CITY},
        {'id': 1005, 'title': 'Усинск', 'type': LocationType.CITY},
        {'id': 1006, 'title': 'Усмань', 'type': LocationType.CITY},
        {'id': 1007, 'title': 'Усолье-Сибирское', 'type': LocationType.CITY},
        {'id': 1008, 'title': 'Усолье', 'type': LocationType.CITY},
        {'id': 1009, 'title': 'Уссурийск', 'type': LocationType.CITY},
        {'id': 1010, 'title': 'Усть-Джегута', 'type': LocationType.CITY},
        {'id': 1011, 'title': 'Усть-Илимск', 'type': LocationType.CITY},
        {'id': 1012, 'title': 'Усть-Катав', 'type': LocationType.CITY},
        {'id': 1013, 'title': 'Усть-Кут', 'type': LocationType.CITY},
        {'id': 1014, 'title': 'Усть-Лабинск', 'type': LocationType.CITY},
        {'id': 1015, 'title': 'Устюжна', 'type': LocationType.CITY},
        {'id': 1016, 'title': 'Уфа', 'type': LocationType.CITY},
        {'id': 1017, 'title': 'Ухта', 'type': LocationType.CITY},
        {'id': 1018, 'title': 'Учалы', 'type': LocationType.CITY},
        {'id': 1019, 'title': 'Уяр', 'type': LocationType.CITY},
        {'id': 1020, 'title': 'Фатеж', 'type': LocationType.CITY},
        {'id': 1021, 'title': 'Феодосия', 'type': LocationType.CITY},
        {'id': 1022, 'title': 'Фокино (Брянская область)', 'type': LocationType.CITY},
        {'id': 1023, 'title': 'Фокино (Приморский край)', 'type': LocationType.CITY},
        {'id': 1024, 'title': 'Фролово', 'type': LocationType.CITY},
        {'id': 1025, 'title': 'Фрязино', 'type': LocationType.CITY},
        {'id': 1026, 'title': 'Фурманов', 'type': LocationType.CITY},
        {'id': 1027, 'title': 'Хабаровск', 'type': LocationType.CITY},
        {'id': 1028, 'title': 'Хадыженск', 'type': LocationType.CITY},
        {'id': 1029, 'title': 'Ханты-Мансийск', 'type': LocationType.CITY},
        {'id': 1030, 'title': 'Харабали', 'type': LocationType.CITY},
        {'id': 1031, 'title': 'Харовск', 'type': LocationType.CITY},
        {'id': 1032, 'title': 'Хасавюрт', 'type': LocationType.CITY},
        {'id': 1033, 'title': 'Хвалынск', 'type': LocationType.CITY},
        {'id': 1034, 'title': 'Хилок', 'type': LocationType.CITY},
        {'id': 1035, 'title': 'Химки', 'type': LocationType.CITY},
        {'id': 1036, 'title': 'Холм', 'type': LocationType.CITY},
        {'id': 1037, 'title': 'Холмск', 'type': LocationType.CITY},
        {'id': 1038, 'title': 'Хотьково', 'type': LocationType.CITY},
        {'id': 1039, 'title': 'Цивильск', 'type': LocationType.CITY},
        {'id': 1040, 'title': 'Цимлянск', 'type': LocationType.CITY},
        {'id': 1041, 'title': 'Циолковский', 'type': LocationType.CITY},
        {'id': 1042, 'title': 'Чадан', 'type': LocationType.CITY},
        {'id': 1043, 'title': 'Чайковский', 'type': LocationType.CITY},
        {'id': 1044, 'title': 'Чапаевск', 'type': LocationType.CITY},
        {'id': 1045, 'title': 'Чаплыгин', 'type': LocationType.CITY},
        {'id': 1046, 'title': 'Чебаркуль', 'type': LocationType.CITY},
        {'id': 1047, 'title': 'Чебоксары', 'type': LocationType.CITY},
        {'id': 1048, 'title': 'Чегем', 'type': LocationType.CITY},
        {'id': 1049, 'title': 'Чекалин', 'type': LocationType.CITY},
        {'id': 1050, 'title': 'Челябинск', 'type': LocationType.CITY},
        {'id': 1051, 'title': 'Чердынь', 'type': LocationType.CITY},
        {'id': 1052, 'title': 'Черемхово', 'type': LocationType.CITY},
        {'id': 1053, 'title': 'Черепаново', 'type': LocationType.CITY},
        {'id': 1054, 'title': 'Череповец', 'type': LocationType.CITY},
        {'id': 1055, 'title': 'Черкесск', 'type': LocationType.CITY},
        {'id': 1056, 'title': 'Чёрмоз', 'type': LocationType.CITY},
        {'id': 1057, 'title': 'Черноголовка', 'type': LocationType.CITY},
        {'id': 1058, 'title': 'Черногорск', 'type': LocationType.CITY},
        {'id': 1059, 'title': 'Чернушка', 'type': LocationType.CITY},
        {'id': 1060, 'title': 'Черняховск', 'type': LocationType.CITY},
        {'id': 1061, 'title': 'Чехов', 'type': LocationType.CITY},
        {'id': 1062, 'title': 'Чистополь', 'type': LocationType.CITY},
        {'id': 1063, 'title': 'Чита', 'type': LocationType.CITY},
        {'id': 1064, 'title': 'Чкаловск', 'type': LocationType.CITY},
        {'id': 1065, 'title': 'Чудово', 'type': LocationType.CITY},
        {'id': 1066, 'title': 'Чулым', 'type': LocationType.CITY},
        {'id': 1067, 'title': 'Чусовой', 'type': LocationType.CITY},
        {'id': 1068, 'title': 'Чухлома', 'type': LocationType.CITY},
        {'id': 1069, 'title': 'Шагонар', 'type': LocationType.CITY},
        {'id': 1070, 'title': 'Шадринск', 'type': LocationType.CITY},
        {'id': 1071, 'title': 'Шали', 'type': LocationType.CITY},
        {'id': 1072, 'title': 'Шарыпово', 'type': LocationType.CITY},
        {'id': 1073, 'title': 'Шарья', 'type': LocationType.CITY},
        {'id': 1074, 'title': 'Шатура', 'type': LocationType.CITY},
        {'id': 1075, 'title': 'Шахты', 'type': LocationType.CITY},
        {'id': 1076, 'title': 'Шахунья', 'type': LocationType.CITY},
        {'id': 1077, 'title': 'Шацк', 'type': LocationType.CITY},
        {'id': 1078, 'title': 'Шебекино', 'type': LocationType.CITY},
        {'id': 1079, 'title': 'Шелехов', 'type': LocationType.CITY},
        {'id': 1080, 'title': 'Шенкурск', 'type': LocationType.CITY},
        {'id': 1081, 'title': 'Шилка', 'type': LocationType.CITY},
        {'id': 1082, 'title': 'Шимановск', 'type': LocationType.CITY},
        {'id': 1083, 'title': 'Шиханы', 'type': LocationType.CITY},
        {'id': 1084, 'title': 'Шлиссельбург', 'type': LocationType.CITY},
        {'id': 1085, 'title': 'Шумерля', 'type': LocationType.CITY},
        {'id': 1086, 'title': 'Шумиха', 'type': LocationType.CITY},
        {'id': 1087, 'title': 'Шуя', 'type': LocationType.CITY},
        {'id': 1088, 'title': 'Щёкино', 'type': LocationType.CITY},
        {'id': 1089, 'title': 'Щёлкино', 'type': LocationType.CITY},
        {'id': 1090, 'title': 'Щёлково', 'type': LocationType.CITY},
        {'id': 1091, 'title': 'Щигры', 'type': LocationType.CITY},
        {'id': 1092, 'title': 'Щучье', 'type': LocationType.CITY},
        {'id': 1093, 'title': 'Электрогорск', 'type': LocationType.CITY},
        {'id': 1094, 'title': 'Электросталь', 'type': LocationType.CITY},
        {'id': 1095, 'title': 'Электроугли', 'type': LocationType.CITY},
        {'id': 1096, 'title': 'Элиста', 'type': LocationType.CITY},
        {'id': 1097, 'title': 'Энгельс', 'type': LocationType.CITY},
        {'id': 1098, 'title': 'Эртиль', 'type': LocationType.CITY},
        {'id': 1099, 'title': 'Югорск', 'type': LocationType.CITY},
        {'id': 1100, 'title': 'Южа', 'type': LocationType.CITY},
        {'id': 1101, 'title': 'Южно-Сахалинск', 'type': LocationType.CITY},
        {'id': 1102, 'title': 'Южно-Сухокумск', 'type': LocationType.CITY},
        {'id': 1103, 'title': 'Южноуральск', 'type': LocationType.CITY},
        {'id': 1104, 'title': 'Юрга', 'type': LocationType.CITY},
        {'id': 1105, 'title': 'Юрьев-Польский', 'type': LocationType.CITY},
        {'id': 1106, 'title': 'Юрьевец', 'type': LocationType.CITY},
        {'id': 1107, 'title': 'Юрюзань', 'type': LocationType.CITY},
        {'id': 1108, 'title': 'Юхнов', 'type': LocationType.CITY},
        {'id': 1109, 'title': 'Ядрин', 'type': LocationType.CITY},
        {'id': 1110, 'title': 'Якутск', 'type': LocationType.CITY},
        {'id': 1111, 'title': 'Ялта', 'type': LocationType.CITY},
        {'id': 1112, 'title': 'Ялуторовск', 'type': LocationType.CITY},
        {'id': 1113, 'title': 'Янаул', 'type': LocationType.CITY},
        {'id': 1114, 'title': 'Яранск', 'type': LocationType.CITY},
        {'id': 1115, 'title': 'Яровое', 'type': LocationType.CITY},
        {'id': 1116, 'title': 'Ярославль', 'type': LocationType.CITY},
        {'id': 1117, 'title': 'Ярцево', 'type': LocationType.CITY},
        {'id': 1118, 'title': 'Ясногорск', 'type': LocationType.CITY},
        {'id': 1119, 'title': 'Ясный', 'type': LocationType.CITY},
        {'id': 1120, 'title': 'Яхрома', 'type': LocationType.CITY},

        #Станции Московсого метро
        {"id": 1121, "title": "Щелковская", "type": LocationType.STATION},
        {"id": 1122, "title": "Первомайская", "type": LocationType.STATION},
        {"id": 1123, "title": "Измайловская", "type": LocationType.STATION},
        {"id": 1124, "title": "Партизанская", "type": LocationType.STATION},
        {"id": 1125, "title": "Семёновская", "type": LocationType.STATION},
        {"id": 1126, "title": "Электрозаводская", "type": LocationType.STATION},
        {"id": 1127, "title": "Бауманская", "type": LocationType.STATION},
        {"id": 1128, "title": "Сретенский бульвар", "type": LocationType.STATION},
        {"id": 1129, "title": "Чкаловская", "type": LocationType.STATION},
        {"id": 1130, "title": "Курская", "type": LocationType.STATION},
        {"id": 1131, "title": "Китай-город", "type": LocationType.STATION},
        {"id": 1132, "title": "Таганская", "type": LocationType.STATION},
        {"id": 1133, "title": "Марксистская", "type": LocationType.STATION},
        {"id": 1134, "title": "Третьяковская", "type": LocationType.STATION},
        {"id": 1135, "title": "Полянка", "type": LocationType.STATION},
        {"id": 1136, "title": "Серпуховская", "type": LocationType.STATION},
        {"id": 1137, "title": "Тульская", "type": LocationType.STATION},
        {"id": 1138, "title": "Нагатинская", "type": LocationType.STATION},
        {"id": 1139, "title": "Нагорная", "type": LocationType.STATION},
        {"id": 1140, "title": "Нахимовский проспект", "type": LocationType.STATION},
        {"id": 1141, "title": "Севастопольская", "type": LocationType.STATION},
        {"id": 1142, "title": "Чертановская", "type": LocationType.STATION},
        {"id": 1143, "title": "Южная", "type": LocationType.STATION},
        {"id": 1144, "title": "Пражская", "type": LocationType.STATION},
        {"id": 1145, "title": "Улица Академика Янгеля", "type": LocationType.STATION},
        {"id": 1146, "title": "Аннино", "type": LocationType.STATION},
        {"id": 1147, "title": "Бульвар Дмитрия Донского", "type": LocationType.STATION},
        {"id": 1148, "title": "Бунинская аллея", "type": LocationType.STATION},
        {"id": 1149, "title": "Улица Скобелевская", "type": LocationType.STATION},
        {"id": 1150, "title": "Беляево", "type": LocationType.STATION},
        {"id": 1151, "title": "Коньково", "type": LocationType.STATION},
        {"id": 1152, "title": "Тёплый Стан", "type": LocationType.STATION},
        {"id": 1153, "title": "Ясенево", "type": LocationType.STATION},
        {"id": 1154, "title": "Новоясеневская", "type": LocationType.STATION},
        {"id": 1155, "title": "Черкизовская", "type": LocationType.STATION},
        {"id": 1156, "title": "Солнцево", "type": LocationType.STATION},
        {"id": 1157, "title": "Проспект Вернадского", "type": LocationType.STATION},
        {"id": 1158, "title": "Юго-Западная", "type": LocationType.STATION},
        {"id": 1159, "title": "Тропарёво", "type": LocationType.STATION},
        {"id": 1160, "title": "Румянцево", "type": LocationType.STATION},
        {"id": 1161, "title": "Саларьево", "type": LocationType.STATION},
        {"id": 1162, "title": "Филатов Луг", "type": LocationType.STATION},
        {"id": 1163, "title": "Прокшино", "type": LocationType.STATION},
        {"id": 1164, "title": "Коммунарка", "type": LocationType.STATION},
        {"id": 1165, "title": "Комсомольская", "type": LocationType.STATION},
        {"id": 1166, "title": "Боровское шоссе", "type": LocationType.STATION},
        {"id": 1167, "title": "Новопеределкино", "type": LocationType.STATION},
        {"id": 1168, "title": "Рассказовка", "type": LocationType.STATION},
        {"id": 1169, "title": "Чистые пруды", "type": LocationType.STATION},
        {"id": 1170, "title": "Библиотека имени Ленина", "type": LocationType.STATION},
    ],
    Flight: [
        #Поезд 1
        {"id": 1, "where_from_id": 607, "where_to_id": 829, "train_id": 1},
        #Поезд 2
        {"id": 2, "where_from_id": 1131, "where_to_id": 1130, "train_id": 2}
    ],
    Ticket: [
        #Билеты на направление Поезда 1
        {"id": 1, "flight_id": 1, "seat_id": 1, "price": 2000.00},
        {"id": 2, "flight_id": 1, "seat_id": 2, "price": 2000.00},
        {"id": 3, "flight_id": 1, "seat_id": 3, "price": 2000.00},
        {"id": 4, "flight_id": 1, "seat_id": 4, "price": 2000.00},
        {"id": 5, "flight_id": 1, "seat_id": 5, "price": 2000.00},
        {"id": 6, "flight_id": 1, "seat_id": 6, "price": 2000.00},
        {"id": 7, "flight_id": 1, "seat_id": 7, "price": 2000.00},
        {"id": 8, "flight_id": 1, "seat_id": 8, "price": 2000.00},
        {"id": 9, "flight_id": 1, "seat_id": 9, "price": 2000.00},
        {"id": 10, "flight_id": 1, "seat_id": 10, "price": 2000.00},
        {"id": 11, "flight_id": 1, "seat_id": 11, "price": 2000.00},
        {"id": 12, "flight_id": 1, "seat_id": 12, "price": 2000.00},
        {"id": 13, "flight_id": 1, "seat_id": 13, "price": 2000.00},
        {"id": 14, "flight_id": 1, "seat_id": 14, "price": 2000.00},
        {"id": 15, "flight_id": 1, "seat_id": 15, "price": 2000.00},
        {"id": 16, "flight_id": 1, "seat_id": 16, "price": 2000.00},
        {"id": 17, "flight_id": 1, "seat_id": 17, "price": 2000.00},
        {"id": 18, "flight_id": 1, "seat_id": 18, "price": 2000.00},
        {"id": 19, "flight_id": 1, "seat_id": 19, "price": 2000.00},
        {"id": 20, "flight_id": 1, "seat_id": 20, "price": 2000.00},
        {"id": 21, "flight_id": 1, "seat_id": 21, "price": 2000.00},
        {"id": 22, "flight_id": 1, "seat_id": 22, "price": 2000.00},
        {"id": 23, "flight_id": 1, "seat_id": 23, "price": 2000.00},
        {"id": 24, "flight_id": 1, "seat_id": 24, "price": 2000.00},
        {"id": 25, "flight_id": 1, "seat_id": 25, "price": 2000.00},
        {"id": 26, "flight_id": 1, "seat_id": 26, "price": 2000.00},
        {"id": 27, "flight_id": 1, "seat_id": 27, "price": 2000.00},
        {"id": 28, "flight_id": 1, "seat_id": 28, "price": 2000.00},
        {"id": 29, "flight_id": 1, "seat_id": 29, "price": 2000.00},
        {"id": 30, "flight_id": 1, "seat_id": 30, "price": 2000.00},
        {"id": 31, "flight_id": 1, "seat_id": 31, "price": 2000.00},
        {"id": 32, "flight_id": 1, "seat_id": 32, "price": 2000.00},
        {"id": 33, "flight_id": 1, "seat_id": 33, "price": 2000.00},
        {"id": 34, "flight_id": 1, "seat_id": 34, "price": 2000.00},
        {"id": 35, "flight_id": 1, "seat_id": 35, "price": 2000.00},
        {"id": 36, "flight_id": 1, "seat_id": 36, "price": 2000.00},
        {"id": 37, "flight_id": 1, "seat_id": 37, "price": 2000.00},
        {"id": 38, "flight_id": 1, "seat_id": 38, "price": 2000.00},
        {"id": 39, "flight_id": 1, "seat_id": 39, "price": 2000.00},
        {"id": 40, "flight_id": 1, "seat_id": 40, "price": 2000.00},
        {"id": 41, "flight_id": 1, "seat_id": 41, "price": 2000.00},
        {"id": 42, "flight_id": 1, "seat_id": 42, "price": 2000.00},
        {"id": 43, "flight_id": 1, "seat_id": 43, "price": 2000.00},
        {"id": 44, "flight_id": 1, "seat_id": 44, "price": 2000.00},
        {"id": 45, "flight_id": 1, "seat_id": 45, "price": 2000.00},
        {"id": 46, "flight_id": 1, "seat_id": 46, "price": 2000.00},
        {"id": 47, "flight_id": 1, "seat_id": 47, "price": 2000.00},
        {"id": 48, "flight_id": 1, "seat_id": 48, "price": 2000.00},
        {"id": 49, "flight_id": 1, "seat_id": 49, "price": 5000.00},
        {"id": 50, "flight_id": 1, "seat_id": 50, "price": 5000.00},
        {"id": 51, "flight_id": 1, "seat_id": 51, "price": 5000.00},
        {"id": 52, "flight_id": 1, "seat_id": 52, "price": 5000.00},
        {"id": 53, "flight_id": 1, "seat_id": 53, "price": 5000.00},
        {"id": 54, "flight_id": 1, "seat_id": 54, "price": 5000.00},
        {"id": 55, "flight_id": 1, "seat_id": 55, "price": 5000.00},
        {"id": 56, "flight_id": 1, "seat_id": 56, "price": 5000.00},
        {"id": 57, "flight_id": 1, "seat_id": 57, "price": 5000.00},
        {"id": 58, "flight_id": 1, "seat_id": 58, "price": 5000.00},
        {"id": 59, "flight_id": 1, "seat_id": 59, "price": 5000.00},
        {"id": 60, "flight_id": 1, "seat_id": 60, "price": 5000.00},

        # Билеты на направление Поезда 2
        {"id": 61, "flight_id": 2, "seat_id": 61, "price": 500.00},
        {"id": 62, "flight_id": 2, "seat_id": 62, "price": 500.00},
        {"id": 63, "flight_id": 2, "seat_id": 63, "price": 500.00},
        {"id": 64, "flight_id": 2, "seat_id": 64, "price": 500.00},
        {"id": 65, "flight_id": 2, "seat_id": 65, "price": 500.00},
        {"id": 66, "flight_id": 2, "seat_id": 66, "price": 500.00},
        {"id": 67, "flight_id": 2, "seat_id": 67, "price": 500.00},
        {"id": 68, "flight_id": 2, "seat_id": 68, "price": 500.00},
        {"id": 69, "flight_id": 2, "seat_id": 69, "price": 500.00},
        {"id": 70, "flight_id": 2, "seat_id": 70, "price": 500.00},
        {"id": 71, "flight_id": 2, "seat_id": 71, "price": 500.00},
        {"id": 72, "flight_id": 2, "seat_id": 72, "price": 500.00},
        {"id": 73, "flight_id": 2, "seat_id": 73, "price": 500.00},
        {"id": 74, "flight_id": 2, "seat_id": 74, "price": 500.00},
        {"id": 75, "flight_id": 2, "seat_id": 75, "price": 500.00},
        {"id": 76, "flight_id": 2, "seat_id": 76, "price": 500.00},
        {"id": 77, "flight_id": 2, "seat_id": 77, "price": 500.00},
        {"id": 78, "flight_id": 2, "seat_id": 78, "price": 500.00},
        {"id": 79, "flight_id": 2, "seat_id": 79, "price": 500.00},
        {"id": 80, "flight_id": 2, "seat_id": 80, "price": 500.00},
        {"id": 81, "flight_id": 2, "seat_id": 81, "price": 500.00},
        {"id": 82, "flight_id": 2, "seat_id": 82, "price": 500.00},
        {"id": 83, "flight_id": 2, "seat_id": 83, "price": 500.00},
        {"id": 84, "flight_id": 2, "seat_id": 84, "price": 500.00},
        {"id": 85, "flight_id": 2, "seat_id": 85, "price": 500.00},
        {"id": 86, "flight_id": 2, "seat_id": 86, "price": 500.00},
        {"id": 87, "flight_id": 2, "seat_id": 87, "price": 500.00},
        {"id": 88, "flight_id": 2, "seat_id": 88, "price": 500.00},
        {"id": 89, "flight_id": 2, "seat_id": 89, "price": 500.00},
        {"id": 90, "flight_id": 2, "seat_id": 90, "price": 500.00},
        {"id": 91, "flight_id": 2, "seat_id": 91, "price": 500.00},
        {"id": 92, "flight_id": 2, "seat_id": 92, "price": 500.00},
        {"id": 93, "flight_id": 2, "seat_id": 93, "price": 500.00},
        {"id": 94, "flight_id": 2, "seat_id": 94, "price": 500.00},
        {"id": 95, "flight_id": 2, "seat_id": 95, "price": 500.00},
        {"id": 96, "flight_id": 2, "seat_id": 96, "price": 500.00}
    ]
}